name: googletest
version: 1.15.2
url: https://github.com/google/googletest/archive/refs/tags/v1.15.2.tar.gz
sha256: 7b42b4d6ed48810c5362c265a17faebe90dc2373c885e5216439d37927f02926
steps:
  a:
    dependencies:
      - abseil-cpp
      - re2
    run: build.bat
