name: pango
version: 1.55.0
url: https://download.gnome.org/sources/pango/1.55/pango-1.55.0.tar.xz
steps:
  one:
    dependencies:
      - pkg-config
      - cairo
      - gobject-introspection
      - glib:two
      - fontconfig
      - freetype
      - fribidi
      - harfbuzz
      - libpng
      - libthai
    run: build.bat
