name: pango
version: 1.54.0
url: https://download.gnome.org/sources/pango/1.54/pango-1.54.0.tar.xz
steps:
  one:
    dependencies:
      - pkg-config
      - cairo
      - glib
      - fontconfig
      - freetype
      - fribidi
      - harfbuzz
      - libpng
      - libthai
    run: build.bat
