name: DyLP
version: 1.10.4
url: https://github.com/coin-or/DyLP/archive/refs/tags/releases/1.10.4.tar.gz
sha256: 5825bede088d78af772cb9a348d10032895d824461c8d22dbd76a70caa8b5b00
steps:
  a:
    dependencies:
      - CoinUtils
      - Osi
      - Data-Sample
      - Data-Netlib
    run: build.sh
