name: flac
version: 1.4.3
url: https://downloads.xiph.org/releases/flac/flac-1.4.3.tar.xz
sha256: 6c58e69cd22348f441b861092b825e591d0b822e106de6eb0ee4d05d27205b70
dependencies:
  required:
    - pkg-config
    - libogg
run: build.bat
