name: OpenEXR
version: 3.3.5
url: https://github.com/AcademySoftwareFoundation/openexr/archive/refs/tags/v3.3.5.tar.gz
sha256: cb0c88710c906c9bfc59027eb147e780d508c7be1a90b43af3ec9e3c2987b70d
dependencies:
  required:
    - Imath
    - libdeflate
    - winpthreads
script: build.bat
