name: boost
version: 1.88.0
url: https://archives.boost.io/release/1.88.0/source/boost_1_88_0.tar.bz2
sha256: 46d9d2c06637b219270877c9e16155cbd015b6dc84349af064c088e9b5b12f7b
dependencies:
  required:
    - pkg-config
    - bzip2
    - icu4c
    - libiconv
    - libjpeg-turbo
    - libpng
    - libtiff
    - openssl
    - xz
    - zlib
    - zstd
    - winpthreads
script: build.bat
