name: libunistring
version: 1.3
url: https://ftp.gnu.org/pub/gnu/libunistring/libunistring-1.3.tar.xz
sha256: f245786c831d25150f3dfb4317cda1acc5e3f79a5da4ad073ddca58886569527
steps:
  a:
    dependencies:
      - dlfcn-win32
      - dirent
      - libiconv
      - winpthreads
    run: build.sh
