name: Cgl
version: master
url: https://github.com/coin-or/Cgl.git
recursive: false
depth: 1
dependencies:
  required:
    - CoinUtils
    - dlfcn-win32
    - Data-Sample
    - Osi
    - Clp
run: build.sh
