name: libiconv
version: 1.18
url: https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.18.tar.gz
sha256: 3b08f5f4f9b4eb82f151a7040bfd6fe6c6fb922efe4b1659c66ea933276965e8
steps:
  a:
    dependencies:
      - dlfcn-win32
      - winpthreads
    run: build.sh
