name: libwebp
version: 1.4.0
url: https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.4.0.tar.gz
sha256: 61f873ec69e3be1b99535634340d5bde750b2e4447caa1db9f61be3fd49ab1e5
steps:
  one:
    dependencies:
      - zlib
      - libpng
      - libjpeg-turbo
      - libtiff
      - giflib
      - winpthreads
      - freeglut
    run: build.bat
