name: libdeflate
version: 1.19
url: https://github.com/ebiggers/libdeflate/archive/refs/tags/v1.19.tar.gz
sha256: 27bf62d71cd64728ff43a9feb92f2ac2f2bf748986d856133cc1e51992428c25
dependencies:
  required:
    - zlib
script: build.bat
