name: graphene
version: 1.10.8
url: https://github.com/ebassi/graphene/archive/refs/tags/1.10.8.tar.gz
sha256: 922dc109d2dc5dc56617a29bd716c79dd84db31721a8493a13a5f79109a4a4ed
steps:
  a:
    dependencies:
      - pkg-config
      - gobject-introspection:b
    run: build.bat
