name: tree-sitter-lua
version: 0.4.0
url: https://github.com/tree-sitter-grammars/tree-sitter-lua/archive/v0.4.0.tar.gz
sha256: b0977aced4a63bb75f26725787e047b8f5f4a092712c840ea7070765d4049559
dependencies:
script: build.bat
