name: openjpeg
version: 2.5.2
url: https://github.com/uclouvain/openjpeg/archive/refs/tags/v2.5.2.tar.gz
sha256: 90e3896fed910c376aaf79cdd98bdfdaf98c6472efd8e1debf0a854938cbda6a
steps:
  a:
    dependencies:
    run: build.bat