name: gmp
version: 6.3.0
url: https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz
sha256: a3c2b80201b89e68616f4ad30bc66aee4927c3ce50e33929ca819d5c43538898
steps:
  one:
    dependencies:
      - dlfcn-win32
      - yasm
    run: build.sh
  two:
    dependencies:
      - dlfcn-win32
      - yasm
    run: build-2.sh
