name: gmp
version: 6.3.0
url: https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz
steps:
  one:
    dependencies:
      - yasm
    run: build.sh
  two:
    dependencies:
      - yasm
    run: build-2.sh
