name: fontconfig
version: 2.15.0
url: https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.15.0.tar.xz
sha256: 63a0658d0e06e0fa886106452b58ef04f21f58202ea02a94c39de0d3335d7c0e
dependencies:
  required:
    - dirent
    - pkg-config
    - getopt
    - gettext
    - glib:required
    - gperf
    - freetype
    - expat
    - harfbuzz:required
script: build.bat
