name: libfishsound
version: 1.0.0
url: https://downloads.xiph.org/releases/libfishsound/libfishsound-1.0.0.tar.gz
sha256: 2e0b57ce2fecc9375eef72938ed08ac8c8f6c5238e1cae24458f0b0e8dade7c7
dependencies:
  required:
    - flac
    - liboggz
    - libvorbis
    - speex
script: build.sh
