name: fmt
version: 11.0.2
url: https://github.com/fmtlib/fmt/archive/11.0.2/fmt-11.0.2.tar.gz
sha256: 6cb1e6d37bdcb756dbbe59be438790db409cdb4868c66e888d5df9f13f7c027f
steps:
  a:
    dependencies:
      - winpthreads
    run: build.bat