name: llvm-project
version: 20.1.8
url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-20.1.8.tar.gz
sha256: a6cbad9b2243b17e87795817cfff2107d113543a12486586f8a055a2bb044963
dependencies:
  required:
    - dlfcn-win32
    - libffi
    - libxml2
    - lua
    - perl
    - xz
    - zlib
    - zstd
    - winpthreads
script: build.bat
