name: ncurses
version: 6.5
url: https://ftp.gnu.org/gnu/ncurses/ncurses-6.5.tar.gz
sha256: 136d91bc269a9a5785e5f9e980bc76ab57428f604ce3e5a5a90cebc767971cc6
steps:
  a:
    dependencies:
      - getopt
      - pcre2:a
      - winpthreads
    run: build.sh
