name: krb5
version: 1.21.3
url: https://kerberos.org/dist/krb5/1.21/krb5-1.21.3.tar.gz
sha256: b7a4cd5ead67fb08b980b21abd150ff7217e85ea320c9ed0c6dadd304840ad35
steps:
  a:
    dependencies:
      - perl
    run: build.bat
