name: mpfrcx
version: 0.6.3
url: https://www.multiprecision.org/downloads/mpfrcx-0.6.3.tar.gz
sha256: 9da9b3614c0a3e00e6ed2b82fc935d1c838d97074dc59cb388f8fafbe3db8594
steps:
  a:
    dependencies:
      - dlfcn-win32
      - yasm
      - gmp:b
      - mpfr
      - mpc
    run: build.sh
