name: sparsehash
version: 2.0.4
url: https://github.com/sparsehash/sparsehash/archive/refs/tags/sparsehash-2.0.4.tar.gz
sha256: 8cd1a95827dfd8270927894eb77f62b4087735cbede953884647f16c521c7e58
steps:
  one:
    dependencies:
    run: build.sh