name: capstone
version: 5.0.3
url: https://github.com/capstone-engine/capstone/archive/refs/tags/5.0.3.tar.gz
sha256: 3970c63ca1f8755f2c8e69b41432b710ff634f1b45ee4e5351defec4ec8e1753
dependencies:
  required:
    - getopt
script: build.bat
