name: libxmlb
version: 0.3.22
url: https://github.com/hughsie/libxmlb/archive/refs/tags/0.3.22.tar.gz
sha256: 103684ed37a45d0aed8f95e97294ed26945b5aeebf44734f3994081eecebb11c
dependencies:
  required:
    - pkg-config
    - glib
    - gobject-introspection
    - llvm-project
    - xz
    - zstd
run: build.bat
