name: libtasn1
version: 4.19.0
url: https://ftp.gnu.org/pub/gnu/libtasn1/libtasn1-4.19.0.tar.gz
sha256: 1613f0ac1cf484d6ec0ce3b8c06d56263cc7242f1c23b30d82d23de345a63f7a
dependencies:
  required:
    - dlfcn-win32
    - getopt
script: build.sh
