name: libidn2
version: 2.3.7
url: https://ftp.gnu.org/gnu/libidn/libidn2-2.3.7.tar.gz
steps:
  one:
    dependencies:
      - dlfcn-win32
      - getopt
      - gettext
      - libiconv
      - libunistring
    run: build.sh
