name: gflags
version: 2.2.2
url: https://github.com/gflags/gflags/archive/refs/tags/v2.2.2.tar.gz
sha256: 34af2f15cf7367513b352bdcd2493ab14ce43692d2dcd9dfc499492966c64dcf
dependencies:
  required:
    - winpthreads
run: build.bat
