name: libxslt
version: 1.1.42
url: https://download.gnome.org/sources/libxslt/1.1/libxslt-1.1.42.tar.xz
sha256: 85ca62cac0d41fc77d3f6033da9df6fd73d20ea2fc18b0a3609ffb4110e1baeb
dependencies:
  required:
    - libxml2
    - winpthreads
run: build.bat
