name: libusb
version: 1.0.27
url: https://github.com/libusb/libusb/archive/refs/tags/v1.0.27.tar.gz
sha256: e8f18a7a36ecbb11fb820bd71540350d8f61bcd9db0d2e8c18a6fb80b214a3de
steps:
  one:
    dependencies:
      - getopt
    run: build.bat
