name: scip
version: 9.2.1
url: https://www.scipopt.org/download/release/scip-9.2.1.tgz
sha256: d22982b1f31e44b111a673acd8250f093c7291303427392a0a8a253738a08258
dependencies:
  required:
    - pkg-config
    - papilo
    - soplex
    - zimpl
    - zlib
    - Ipopt
    - winpthreads
run: build.bat
