name: make
version: 4.4
url: https://ftp.gnu.org/pub/gnu/make/make-4.4.tar.gz
sha256: 581f4d4e872da74b3941c874215898a7d35802f03732bdccee1d4a7979105d18
steps:
  a:
    dependencies:
      - getopt
    run: build.bat
