name: pixman
version: 0.43.4
url: https://www.cairographics.org/releases/pixman-0.43.4.tar.gz
sha256: a0624db90180c7ddb79fc7a9151093dc37c646d8c38d3f232f767cf64b85a226
steps:
  a:
    dependencies:
      - pkg-config
      - libpng
      - glib:b
      - zlib
      - winpthreads
    run: build.bat