name: pixman
version: 0.44.2
url: https://www.cairographics.org/releases/pixman-0.44.2.tar.xz
sha256: 50baf820dde0c5ff9714d03d2df4970f606a3d3b1024f5404c0398a9821cc4b0
dependencies:
  required:
    - pkg-config
    - libpng
    - glib
    - zlib
    - winpthreads
run: build.bat
