name: zlib-ng
version: 2.2.4
url: https://github.com/zlib-ng/zlib-ng/archive/refs/tags/2.2.4.tar.gz
sha256: a73343c3093e5cdc50d9377997c3815b878fd110bf6511c2c7759f2afb90f5a3
steps:
  a:
    dependencies:
    run: build.bat
