name: libraqm
version: 0.10.2
url: https://github.com/HOST-Oman/libraqm/archive/refs/tags/v0.10.2.tar.gz
sha256: db68fd9f034fc40ece103e511ffdf941d69f5e935c48ded8a31590468e42ba72
dependencies:
  required:
    - pkg-config
    - freetype
    - harfbuzz
    - fribidi
script: build.bat
