name: libjxl
version: v0.11.1
url: https://github.com/libjxl/libjxl.git
recursive: true
depth: 1
submodules:
  third_party/skcms:
    url: https://github.com/google/skcms
    branch: mirror
dependencies:
  required:
    - pkg-config
    - highway
    - brotli
    - googletest
    - highway
    - lcms2
    - libwebp
    - libavif
    - sjpeg
    - zlib
    - libpng
    - libjpeg-turbo
run: build.bat
