name: libjxl
version: 0.11.1
url: https://github.com/libjxl/libjxl/archive/refs/tags/v0.11.1.tar.gz
sha256: 1492dfef8dd6c3036446ac3b340005d92ab92f7d48ee3271b5dac1d36945d3d9
steps:
  one:
    dependencies:
      - pkg-config
      - highway
      - llvm-project
      - brotli
      - googletest
      - highway
      - lcms2
      - libwebp
      - libavif
      - sjpeg
      - zlib
      - libpng
      - libjpeg-turbo
    run: build.bat
