name: libthai
version: 0.1.29
url: https://github.com/tlwg/libthai/archive/refs/tags/v0.1.29.tar.gz
sha256: 75b001487322bc8017f4c1d61bbe5d59212b60a24e8794f590b1af910ae20041
steps:
  a:
    dependencies:
      - dlfcn-win32
      - getopt
      - libdatrie
      - llvm-project
    run: build.sh
