name: dng_sdk
version: 1.7.1
url: https://download.adobe.com/pub/adobe/dng/dng_sdk_1_7_1.zip
sha256: 5366d9abd0e623858573bfaf0291b5e352d704f51b322753a22f82af3ae6e0c2
steps:
  a:
    dependencies:
      - libjpeg-turbo
      - libjxl
      - llvm-project
      - XMP-Toolkit-SDK
    run: build.bat
