name: speex
version: 1.2.1
url: https://downloads.xiph.org/releases/speex/speex-1.2.1.tar.gz
sha256: 4b44d4f2b38a370a2d98a78329fefc56a0cf93d1c1be70029217baae6628feea
steps:
  a:
    dependencies:
      - libogg
      - speexdsp
      - llvm-project
    run: build.sh
