name: c-ares
version: 1.34.2
url: https://github.com/c-ares/c-ares/archive/refs/tags/v1.34.2.tar.gz
sha256: ddedac85d77662a88501f07fc9cbae18df8f30850d97ec6432f092b933e32922
dependencies:
  required:
    - dlfcn-win32
script: build.bat
