name: scalapack
version: 2.2.0
url: https://github.com/Reference-ScaLAPACK/scalapack/archive/refs/tags/v2.2.0.tar.gz
sha256: 8862fc9673acf5f87a474aaa71cd74ae27e9bbeee475dbd7292cec5b8bcbdcf3
steps:
  one:
    dependencies:
      - OpenBLAS
      - lapack
    run: build.bat
