name: gobject-introspection
version: 1.82.0
url: https://gitlab.gnome.org/GNOME/gobject-introspection/-/archive/1.82.0/gobject-introspection-1.82.0.tar.bz2
sha256: f62ecd28fc4d641bcbae47d56fb7328beb1877b4bbdb648424d9b83e9e0496a5
steps:
  a:
    dependencies:
      - pkg-config
      - pcre2:a
      - glib:a
      - libffi
      - winflexbison
      - zlib
    run: build.bat
  b:
    dependencies:
      - gobject-introspection:a
      - pkg-config
      - pcre2:a
      - glib:b
      - cairo
      - libffi
      - winflexbison
      - zlib
    run: build.bat
