name: libvorbis
version: 1.3.7
url: https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.tar.xz
sha256: b33cc4934322bcbf6efcbacf49e3ca01aadbea4114ec9589d1b1e9d20f72954b
steps:
  one:
    dependencies:
    run: build.bat
