name: spral
version: 2025.03.06
url: https://github.com/ralna/spral/archive/refs/tags/v2025.03.06.tar.gz
sha256: 1da8576a64a415166d12b529cd30977a1917d2867509f9cb6682aaab2a57b21c
dependencies:
  required:
    - hwloc
    - lapack
    - METIS
    - winpthreads
run: build.sh
