name: spral
version: 2025.01.08
url: https://github.com/ralna/spral/archive/refs/tags/v2025.01.08.tar.gz
sha256: c141878e36cb01a3c6f5e677a43d0f7781781755036f59ef91f38090a8f26f71
steps:
  a:
    dependencies:
      - lapack
      - METIS
      - hwloc
      - llvm-project
    run: build.bat
