name: mesa
version: 25.0.2
url: https://archive.mesa3d.org/mesa-25.0.2.tar.xz
sha256: adf904d083b308df95898600ffed435f4b5c600d95fb6ec6d4c45638627fdc97
steps:
  a:
    dependencies:
      - pkg-config
      - DirectX-Headers
      - freeglut
      - llvm-project
      - winflexbison
      - libva
    run: build.bat
