name: libxml2
version: 2.13.5
url: https://download.gnome.org/sources/libxml2/2.13/libxml2-2.13.5.tar.xz
sha256: 74fc163217a3964257d3be39af943e08861263c4231f9ef5b496b6f6d4c7b2b6
steps:
  a:
    dependencies:
      - icu4c
      - libiconv
      - xz
      - zlib
      - winpthreads
    run: build.bat
