name: libxml2
version: 2.13.5
url: https://download.gnome.org/sources/libxml2/2.13/libxml2-2.13.5.tar.xz
steps:
  one:
    dependencies:
      - icu4c
      - libiconv
      - xz
      - zlib
      - winpthreads
    run: build.bat
