name: liboqs
version: 0.12.0
url: https://github.com/open-quantum-safe/liboqs/archive/refs/tags/0.12.0.tar.gz
sha256: df999915204eb1eba311d89e83d1edd3a514d5a07374745d6a9e5b2dd0d59c08
dependencies:
script: build.bat
