name: Bonmin
version: master
url: https://github.com/coin-or/Bonmin.git
sha256:
steps:
  a:
    dependencies:
      - CoinUtils
      - ThirdParty-HSL
      - ThirdParty-ASL
      - ThirdParty-Mumps
      - ThirdParty-Metis
      - Data-Sample
      - Bcp
      - Osi
      - Clp
      - Cgl
      - Cbc
      - Ipopt
      - lapack
    run: build.sh
