name: libde265
version: 1.0.15
url: https://github.com/strukturag/libde265/archive/refs/tags/v1.0.15.tar.gz
sha256: d4e55706dfc5b2c5c9702940b675ce2d3e7511025c6894eaddcdbaf0b15fd3f3
dependencies:
  required:
    - getopt
    - libvideogfx
    - SDL2
script: build.bat
