name: libtool
version: 2.5.3
url: https://ftp.gnu.org/pub/gnu/libtool/libtool-2.5.3.tar.xz
sha256: 898011232cc59b6b3bbbe321b60aba9db1ac11578ab61ed0df0299458146ae2e
dependencies:
  required:
    - dlfcn-win32
    - dirent
    - m4
run: build.sh
