name: glib
version: 2.83.3
url: https://download.gnome.org/sources/glib/2.83/glib-2.83.3.tar.xz
sha256: d0c65318bb2e3fa594277cf98a71cffaf5f666c078db39dcec121757b2ba328d
steps:
  a:
    dependencies:
      - dlfcn-win32
      - dirent
      - pkg-config
      - gettext
      - libffi
      - pcre2:a
      - zlib
    run: build.bat
  b:
    dependencies:
      - glib:a
      - dlfcn-win32
      - dirent
      - pkg-config
      - gettext
      - libffi
      - gobject-introspection:a
      - pcre2:b
      - zlib
    run: build-2.bat
