name: glib
version: 2.82.1
url: https://download.gnome.org/sources/glib/2.82/glib-2.82.1.tar.xz
sha256: 478634440bf52ee4ec4428d558787398c0be6b043c521beb308334b3db4489a6
steps:
  a:
    dependencies:
      - dlfcn-win32
      - pkg-config
      - gettext
      - libffi
      - pcre2:b
      - zlib
    run: build.bat
  b:
    dependencies:
      - dlfcn-win32
      - pkg-config
      - gettext
      - libffi
      - gobject-introspection
      - pcre2:b
      - zlib
    run: build.bat
