name: libva
version: 2.22.0
url: https://github.com/intel/libva/archive/refs/tags/2.22.0.tar.gz
sha256: 467c418c2640a178c6baad5be2e00d569842123763b80507721ab87eb7af8735
dependencies:
  required:
    - pkg-config
run: build.bat
