name: SYMPHONY
version: master
url: https://github.com/coin-or/SYMPHONY.git
recursive: false
depth: 1
dependencies:
  required:
    - CoinUtils
    - ThirdParty-Glpk
    - Data-Sample
    - Data-Netlib
    - Data-miplib3
    - Osi
    - Clp
    - Cgl
    - DyLP
    - Vol
script: build.sh
