name: libao
version: 1.2.0
url: https://downloads.xiph.org/releases/ao/libao-1.2.0.tar.gz
sha256: 03ad231ad1f9d64b52474392d63c31197b0bc7bd416e58b1c10a329a5ed89caf
dependencies:
  required:
    - dlfcn-win32
    - winpthreads
    - llvm-project
run: build.sh
