name: SuiteSparse
version: 7.10.3
url: https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/refs/tags/v7.10.3.tar.gz
sha256: 09e7bcc8e5de0a5b55d2ae9fd6378d5f4dc1b85a933593339a0872b24e2cc102
dependencies:
  required:
    - gmp
    - lz4
    - mpfr
    - OpenBLAS
    - winpthreads
    - zstd
script: build.bat
