name: OpenCV
version: 4.12.0
url: https://github.com/opencv/opencv/archive/refs/tags/4.12.0.tar.gz
sha256: 44c106d5bb47efec04e531fd93008b3fcd1d27138985c5baf4eafac0e1ec9e9d
dependencies:
  required:
    - ffmpeg
    - libpng
    - libtiff
    - libwebp
    - nasm
    - oneTBB
    - OpenEXR
    - openblas
    - openjpeg
    - zlib
script: build.bat
