#! /bin/sh
# Wrapper for as to ml which do not understand as's command line syntax.

scriptversion=2024-03-08.03; # UTC

nl='
'

# We need space, tab and new line, in precisely that order.  Quoting is
# there to prevent tools from complaining about whitespace usage.
IFS=" ""	$nl"

file_conv=

# func_file_conv build_file lazy
# Convert a $build file to $host form and store it in $file
# Currently only supports Windows hosts. If the determined conversion
# type is listed in (the comma separated) LAZY, no conversion will
# take place.
func_file_conv ()
{
  file=$1
  case $file in
    / | /[!/]*) # absolute file, and not a UNC file
      if test -z "$file_conv"; then
        # lazily determine how to convert abs files
        case `uname -s` in
          MINGW*)
            file_conv=mingw
            ;;
          CYGWIN* | MSYS*)
            file_conv=cygwin
            ;;
          Linux)
            case `uname -r | sed -n 's/.*\( *Microsoft *\).*/\1/p'` in
              Microsoft )
                file_conv=wsl
                ;;
              * )
                echo [$0] Unknown kernel
                exit 1
                ;;
            esac
            ;;
          *)
            file_conv=wine
            ;;
        esac
      fi
      case $file_conv/,$2, in
        *,$file_conv,*)
          ;;
        mingw/*)
          file=`cmd //C echo "$file " | sed -e 's/"\(.*\) " *$/\1/'`
          ;;
        cygwin/* | msys/*)
          file=`cygpath -m "$file" || echo "$file"`
          ;;
        wine/*)
          file=`winepath -w "$file" || echo "$file"`
          ;;
        wsl/*)
          file=`wslpath -m "$file" || echo "$file"`
          ;;
      esac
      ;;
  esac
}

# func_ml_wrapper as arg...
# Adjust compile command to suit as
func_ml_wrapper ()
{
  sfile=
  asmfile=
  defines=
  includes=
  outdir=
  for arg
  do
    if test -n "$eat"; then
      eat=
    else
      case $1 in
        -o)
          eat=1
          outdir="$(dirname $2)"
          case $2 in
            *.o | *.[oO][bB][jJ])
              func_file_conv "$2"
              set x "$@" -Fo"$file"
              ;;
            *)
              func_file_conv "$2"
              set x "$@" -Fe"$file"
              ;;
          esac
          shift
          ;;
        *.asm | *.OBJ | *.obj | *.[oO])
          func_file_conv "$1" mingw
          set x "$@" "$file"
          shift
          ;;
        -D* | -D*=*)
          defines="$defines $1"
          ;;
        -I)
          eat=1
          func_file_conv "$2" mingw
          includes="$includes -I$file"
          ;;
        -I*)
          func_file_conv "${1#-I}" mingw
          includes="$includes -I$file"
          ;;
        *.S)
          func_file_conv "$1"
          sfile=$file
          ;;
        *)
          set x "$@" "$1"
          shift
          ;;
      esac
    fi
    shift
  done
  if test -n "$sfile"; then
    asmfile="$outdir/$(basename $sfile|sed 's/.S$/.asm/g')"
    eval "cl -nologo -EP $includes $defines $sfile" > $asmfile
  fi
  exec "$@" $asmfile
  exit 1
}

eat=

case $1 in
  '')
     echo "$0: No command.  Try '$0 --help' for more information." 1>&2
     exit 1;
     ;;
  -h | --h*)
    cat <<\EOF
Usage: as-ml [--help] [--version] PROGRAM [ARGS]

Wrapper for compilers which do not understand '-c -o'.
Remove '-o dest.o' from ARGS, run PROGRAM with the remaining
arguments, and rename the output as expected.

If you are trying to build a whole package this is not the
right script to run: please start by reading the file 'INSTALL'.

Report bugs to <bug-automake@gnu.org>.
EOF
    exit $?
    ;;
  -v | --v*)
    echo "as-ml $scriptversion"
    exit $?
    ;;
  ml | *[/\\]ml | ml.exe | *[/\\]ml.exe | \
    ml64 | *[/\\]ml64 | ml64.exe | *[/\\]ml64.exe )
    func_ml_wrapper "$@"      # Doesn't return...
    ;;
esac

# Local Variables:
# mode: shell-script
# sh-indentation: 2
# eval: (add-hook 'before-save-hook 'time-stamp)
# time-stamp-start: "scriptversion="
# time-stamp-format: "%:y-%02m-%02d.%02H"
# time-stamp-time-zone: "UTC0"
# time-stamp-end: "; # UTC"
# End:
