#!/bin/bash
#
# Jianshan Jiang modified it from mpiicc.bat
#
# Copyright Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials,
# and your use of them is governed by the express license under which they
# were provided to you (License). Unless the License provides otherwise,
# you may not use, modify, copy, publish, distribute, disclose or transmit
# this software or the related documents without Intel's prior written
# permission.
#
# This software and the related documents are provided as is, with no
# express or implied warranties, other than those that are expressly stated
# in the License.

# ----------------------------------------------------------------------------
# mpiicc
# Simple script to compile and/or link MPI programs by Intel® C++ Compiler.
# This script sets some variable and the general script.
# ----------------------------------------------------------------------------

dir=$(dirname "$0")
if [ $# -eq 0 ] ; then
	"$dir"/mpicc
else
	"$dir"/mpicc -cc=icx-cl "$@"
fi
