name: XMP-Toolkit-SDK
version: 2025.03
url: https://github.com/adobe/XMP-Toolkit-SDK/archive/refs/tags/v2025.03.tar.gz
sha256: 17d641cb1d8b9aba810b229024ec3b181f551f301200264aa1a5c35e4eac9d6e
steps:
  a:
    dependencies:
      - boost
      - expat
      - zlib
    run: build.bat
