name: XMP-Toolkit-SDK
version: 2025.03
url: https://github.com/adobe/XMP-Toolkit-SDK/archive/refs/tags/v2025.03.tar.gz
sha256: 17d641cb1d8b9aba810b229024ec3b181f551f301200264aa1a5c35e4eac9d6e
extras:
  - name: expat
    version: 2.4.7
    url: https://github.com/libexpat/libexpat/archive/refs/tags/R_2_4_7.tar.gz
    sha256: ddc1111651cdd4095b67c9d9ed46babfb8fb64843d89ff785399f5739b84867b
    extract: libexpat-R_2_4_7/expat/lib
    target: third-party/expat/lib
    check: "if not exist \"third-party\\expat\\lib\\xmlparse.c\" (exit 0) else (exit 1)"
  - name: zlib
    version: 1.2.13
    url: https://www.zlib.net/fossils/zlib-1.2.13.tar.gz
    sha256: b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30
    target: third-party/zlib
    check: "if not exist \"third-party\\zlib\\zlib.h\" (exit 0) else (exit 1)"
    include:
      - zlib-1.2.13/adler32.c
      - zlib-1.2.13/compress.c
      - zlib-1.2.13/crc32.c
      - zlib-1.2.13/deflate.c
      - zlib-1.2.13/gzclose.c
      - zlib-1.2.13/gzlib.c
      - zlib-1.2.13/gzread.c
      - zlib-1.2.13/gzwrite.c
      - zlib-1.2.13/infback.c
      - zlib-1.2.13/inffast.c
      - zlib-1.2.13/inflate.c
      - zlib-1.2.13/inftrees.c
      - zlib-1.2.13/trees.c
      - zlib-1.2.13/uncompr.c
      - zlib-1.2.13/zutil.c
      - zlib-1.2.13/crc32.h
      - zlib-1.2.13/deflate.h
      - zlib-1.2.13/gzguts.h
      - zlib-1.2.13/inffast.h
      - zlib-1.2.13/inffixed.h
      - zlib-1.2.13/inflate.h
      - zlib-1.2.13/inftrees.h
      - zlib-1.2.13/trees.h
      - zlib-1.2.13/zconf.h
      - zlib-1.2.13/zlib.h
      - zlib-1.2.13/zutil.h
dependencies:
  required:
    - boost
    - expat
    - zlib
run: build.bat
