name: libffi
version: 3.4.6
url: https://github.com/libffi/libffi/releases/download/v3.4.6/libffi-3.4.6.tar.gz
sha256: b0dea9df23c863a7a50e825440f3ebffabd65df1497108e5d437747843895a4e
dependencies:
  required:
    - dlfcn-win32
script: build.sh
