name: protobuf
version: 31.1
url: https://github.com/protocolbuffers/protobuf/archive/refs/tags/v31.1.tar.gz
sha256: c3a0a9ece8932e31c3b736e2db18b1c42e7070cd9b881388b26d01aa71e24ca2
dependencies:
  required:
    - abseil-cpp
    - winpthreads
    - zlib
script: build.bat
