name: mpc
version: 1.3.1
url: https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz
sha256: ab642492f5cf882b74aa0cb730cd410a81edcdbec895183ce930e706c1c759b8
steps:
  one:
    dependencies:
      - dlfcn-win32
      - yasm
      - gmp:two
      - mpfr
    run: build.sh
