name: automake
version: 1.16.5
url: https://ftp.gnu.org/pub/gnu/automake/automake-1.16.5.tar.xz
sha256: f01d58cd6d9d77fbdca9eb4bbd5ead1988228fdb73d6f7a201f5f8d6b118b469
dependencies:
  required:
    - autoconf
run: build.sh
