name: zstd
version: 1.5.6
url: https://github.com/facebook/zstd/archive/refs/tags/v1.5.6.tar.gz
sha256: 30f35f71c1203369dc979ecde0400ffea93c27391bfd2ac5a9715d2173d92ff7
steps:
  a:
    dependencies:
      - lz4
      - xz
      - zlib
    run: build.bat
