name: pcre2
version: 10.44
url: https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.44/pcre2-10.44.tar.bz2
sha256: d34f02e113cf7193a1ebf2770d3ac527088d485d4e047ed10e5d217c6ef5de96
dependencies:
  required:
    - dirent
    - bzip2
    - zlib
  optional:
    - readline
run: build.bat
