name: x265
version: 3.6
url: https://bitbucket.org/multicoreware/x265_git/downloads/x265_3.6.tar.gz
sha256: 663531f341c5389f460d730e62e10a4fcca3428ca2ca109693867bc5fe2e2807
steps:
  one:
    dependencies:
      - getopt
      - nasm
    run: build.bat
