name: libatomic_ops
version: 7.8.2
url: https://github.com/ivmai/libatomic_ops/archive/refs/tags/v7.8.2.tar.gz
sha256: ad8428a40e01d41bc4ddad3166afa1fc175c9e58d8ef7ddbd7ef3298e32ac37b
steps:
  one:
    dependencies:
      - winpthreads
    run: build.bat
