name: CHiPPS-ALPS
version: 1.5.12
url: https://github.com/coin-or/CHiPPS-ALPS/archive/refs/tags/releases/1.5.12.tar.gz
sha256: b781e32c0e1bedd3ba7eddf72943408693e314377879ee3ef8ef562aa94bbdfc
dependencies:
  required:
    - BuildTools
    - CoinUtils
    - Osi
    - Clp
    - Cgl
script: build.sh
