name: highway
version: 1.2.0
url: https://github.com/google/highway/archive/refs/tags/1.2.0.tar.gz
sha256: 7e0be78b8318e8bdbf6fa545d2ecb4c90f947df03f7aadc42c1967f019e63343
steps:
  a:
    dependencies:
      - winpthreads
    run: build.bat
