name: autoconf
version: 2.72
url: https://ftp.gnu.org/pub/gnu/autoconf/autoconf-2.72.tar.xz
sha256: ba885c1319578d6c94d46e9b0dceb4014caafe2490e437a0dbca3f270a223f5a
steps:
  one:
    dependencies:
      - m4
    run: build.sh
