name: Osi
version: master
url: https://github.com/coin-or/Osi.git
sha256:
steps:
  a:
    dependencies:
      - CoinUtils
      - ThirdParty-Glpk
      - Data-Sample
      - Data-Netlib
    run: build.sh
