name: Osi
version: 0.108.11
url: https://github.com/coin-or/Osi/archive/refs/tags/releases/0.108.11.tar.gz
sha256: 1063b6a057e80222e2ede3ef0c73c0c54697e0fee1d913e2bef530310c13a670
steps:
  a:
    dependencies:
    run: build.sh
