name: fftw
version: 3.3.10
url: https://www.fftw.org/fftw-3.3.10.tar.gz
sha256: 56c932549852cddcfafdab3820b0200c7742675be92179e59e6215b340e26467
steps:
  a:
    dependencies:
    run: build.sh
  b:
    dependencies:
      - fftw:a
    run: build-2.sh
