name: grep
version: 3.11
url: https://ftp.gnu.org/gnu/grep/grep-3.11.tar.xz
sha256: 1db2aedde89d0dea42b16d9528f894c8d15dae4e190b59aecc78f5a951276eab
dependencies:
  required:
    - dirent
    - getopt
    - libsigsegv
    - libiconv
    - gettext
    - pcre2
    - winpthreads
run: build.sh
