name: jasper
version: 4.2.5
url: https://github.com/jasper-software/jasper/archive/refs/tags/version-4.2.5.tar.gz
sha256: 3f4b1df7cab7a3cc67b9f6e28c730372f030b54b0faa8548a9ee04ae83fffd44
dependencies:
  required:
    - libjpeg-turbo
    - libheif:required
    - freeglut
run: build.bat
