name: libpng
version: 1.6.44
url: https://github.com/pnggroup/libpng/archive/refs/tags/v1.6.44.tar.gz
sha256: 0ef5b633d0c65f780c4fced27ff832998e71478c13b45dfb6e94f23a82f64f7c
dependencies:
  required:
    - zlib
script: build.bat
