name: Data-Netlib
version: 1.2.11
url: https://github.com/coin-or-tools/Data-Netlib/archive/refs/tags/releases/1.2.11.tar.gz
sha256: 68876fbd33f0f99d4ccf1f02fe203947fe758a42eac5d5e795e2fca051735791
dependencies:
run: build.sh
