name: libtiff
version: 4.6.0
url: https://download.osgeo.org/libtiff/tiff-4.6.0.tar.xz
sha256: e178649607d1e22b51cf361dd20a3753f244f022eefab1f2f218fc62ebaf87d2
steps:
  a:
    dependencies:
      - getopt
      - libdeflate
      - libjpeg-turbo
      - xz
      - zlib
      - zstd
    run: build.bat
  b:
    dependencies:
      - libtiff:a
      - getopt
      - libdeflate
      - libjpeg-turbo
      - xz
      - zlib
      - zstd
      - libwebp
    run: build.bat
