name: libRaw
version: 0.21.4
url: https://www.libraw.org/data/LibRaw-0.21.4.tar.gz
sha256: 6be43f19397e43214ff56aab056bf3ff4925ca14012ce5a1538a172406a09e63
steps:
  a:
    dependencies:
      - jasper
      - lcms2
      - libjpeg-turbo
      - libiconv
      - libxml2
      - rawspeed
      - XMP-Toolkit-SDK
      - zlib
    run: build.sh
