name: Catch2
version: 3.7.1
url: https://github.com/catchorg/Catch2/archive/refs/tags/v3.7.1.tar.gz
sha256: c991b247a1a0d7bb9c39aa35faf0fe9e19764213f28ffba3109388e62ee0269c
dependencies:
script: build.bat
