name: CoinUtils
version: 2.11.12
url: https://github.com/coin-or/CoinUtils/archive/refs/tags/releases/2.11.12.tar.gz
sha256: eef1785d78639b228ae2de26b334129fe6a7d399c4ac6f8fc5bb9054ba00de64
steps:
  a:
    dependencies:
      - bzip2
      - lapack
      - ThirdParty-Glpk
      - zlib
    run: build.sh
