name: CoinUtils
version: master
url: https://github.com/coin-or/Osi.git
sha256:
steps:
  a:
    dependencies:
      - bzip2
      - dlfcn-win32
      - Data-Sample
      - Data-Netlib
      - ThirdParty-ASL
      - ThirdParty-Glpk
      - zlib
      - readline
    run: build.sh
