name: icu4c
version: 75-1
url: https://github.com/unicode-org/icu/releases/download/release-75-1/icu4c-75_1-src.tgz
sha256: cb968df3e4d2e87e8b11c49a5d01c787bd13b9545280fc6642f826527618caef
extras:
  - name: icu4c-data
    version: 75-1
    url: https://github.com/unicode-org/icu/releases/download/release-75-1/icu4c-75_1-data.zip
    sha256: a5104212dc317a64f9b035723ea706f2f4fd5a0f37b7923fae7aeb9d1d0061b1
    target: source/data
    check: "if not exist \"source\\data\\locales\" (exit 0) else (exit 1)"
dependencies:
  required:
    - dlfcn-win32
    - dirent
    - winpthreads
run: build.sh
