name: icu4c
version: 75-1
url: https://github.com/unicode-org/icu/releases/download/release-75-1/icu4c-75_1-src.tgz
sha256: cb968df3e4d2e87e8b11c49a5d01c787bd13b9545280fc6642f826527618caef
steps:
  a:
    dependencies:
      - dlfcn-win32
      - winpthreads
    run: build.sh
