name: FlopCpp
version: 1.2.5
url: https://github.com/coin-or/FlopCpp/archive/refs/tags/releases/1.2.5.tar.gz
sha256: 789d2ad3631d35b26205beaab3c93aa1bbc5a08df01fad1c3e46c88789c94fb0
steps:
  a:
    dependencies:
      - BuildTools
      - CoinUtils
      - Cbc
      - Cgl
      - Clp
      - Osi
    run: build.sh
