name: Cbc
version: master
url: https://github.com/coin-or/Cbc.git
sha256:
steps:
  a:
    dependencies:
      - CoinUtils
      - ThirdParty-ASL
      - ThirdParty-Glpk
      - ThirdParty-Mumps
      - Data-Sample
      - Data-Netlib
      - Data-miplib3
      - Osi
      - Clp
      - Cgl
    run: build.sh
