name: Clp
version: master
url: https://github.com/coin-or/Clp.git
recursive: false
depth: 1
dependencies:
  required:
    - CoinUtils
    - dlfcn-win32
    - ThirdParty-Glpk
    - ThirdParty-Mumps
    - Data-Sample
    - Data-Netlib
    - Osi
    - readline
    - SuiteSparse
run: build.sh
