name: cairo
version: 1.18.2
url: https://www.cairographics.org/releases/cairo-1.18.2.tar.xz
sha256: a62b9bb42425e844cc3d6ddde043ff39dbabedd1542eba57a2eb79f85889d45a
steps:
  a:
    dependencies:
      - pkg-config
      - fontconfig
      - freetype
      - libpng
      - glib:b
      - libffi
      - libatomic_ops
      - lzo
      - pixman
      - zlib
      - winpthreads
    run: build.bat
