name: cairo
version: 1.18.0
url: https://www.cairographics.org/releases/cairo-1.18.0.tar.xz
sha256: 243a0736b978a33dee29f9cca7521733b78a65b5418206fef7bd1c3d4cf10b64
steps:
  one:
    dependencies:
      - pkg-config
      - fontconfig
      - freetype
      - libpng
      - glib:two
      - libffi
      - libatomic_ops
      - lzo
      - pixman
      - zlib
      - winpthreads
    run: build.bat
