name: readline
version: 8.2.13
url: https://ftp.gnu.org/gnu/readline/readline-8.2.13.tar.gz
sha256: 0e5be4d2937e8bd9b7cd60d46721ce79f88a33415dd68c2d738fb5924638f656
steps:
  a:
    dependencies:
      - dirent
      - getopt
      - pcre:a
      - ncurses
    run: build.sh
