name: SVT-AV1
version: 2.3.0
url: https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v2.3.0/SVT-AV1-v2.3.0.tar.bz2
sha256: f65358499f572a47d6b076dda73681a8162b02c0b619a551bc2d62ead8ee719a
dependencies:
  required:
    - nasm
    - winpthreads
run: build.bat
