name: expat
version: 2.6.2
url: https://github.com/libexpat/libexpat/releases/download/R_2_6_2/expat-2.6.2.tar.bz2
sha256: 9c7c1b5dcbc3c237c500a8fb1493e14d9582146dd9b42aa8d3ffb856a3b927e0
steps:
  one:
    dependencies:
      - dlfcn-win32
    run: build.bat
