name: glib
version: 2.83.3
url: https://download.gnome.org/sources/glib/2.83/glib-2.83.3.tar.xz
sha256: d0c65318bb2e3fa594277cf98a71cffaf5f666c078db39dcec121757b2ba328d
dependencies:
  required:
    - dlfcn-win32
    - dirent
    - pkg-config
    - gettext
    - libffi
    - pcre2
    - zlib
  optional:
    - gobject-introspection:required
script: build.bat
