name: tree-sitter-vimdoc
version: 4.0.0
url: https://github.com/neovim/tree-sitter-vimdoc/archive/v4.0.0.tar.gz
sha256: 8096794c0f090b2d74b7bff94548ac1be3285b929ec74f839bd9b3ff4f4c6a0b
dependencies:
run: build.bat
