name: curl
version: 8.10.1
url: https://curl.se/download/curl-8.10.1.tar.xz
sha256: 73a4b0e99596a09fa5924a4fb7e4b995a85fda0d18a2c02ab9cf134bebce04ee
dependencies:
  required:
    - libidn2
    - libpsl
    - libssh2
    - nghttp2
    - perl
    - zlib
script: build.bat
