name: boost
version: 1.86.0
url: https://archives.boost.io/release/1.86.0/source/boost_1_86_0.tar.bz2
sha256: 1bed88e40401b2cb7a1f76d4bab499e352fa4d0c5f31c0dbae64e24d34d7513b
steps:
  a:
    dependencies:
      - pkg-config
      - bzip2
      - icu4c
      - libiconv
      - libjpeg-turbo
      - libpng
      - libtiff:b
      - openssl
      - xz
      - zlib
      - zstd
      - winpthreads
    run: build.bat
