name: libsigc++
version: 3.6.0
url: https://download.gnome.org/sources/libsigc++/3.6/libsigc++-3.6.0.tar.xz
sha256: c3d23b37dfd6e39f2e09f091b77b1541fbfa17c4f0b6bf5c89baef7229080e17
dependencies:
  required:
    - pkg-config
    - boost
    - libxslt
    - mm-common
script: build.bat
