name: MibS
version: 1.2.2
url: https://github.com/coin-or/MibS/archive/refs/tags/releases/1.2.2.tar.gz
sha256: 54c43d5ac3bf179922b50516205621aca480a41840758ae8f480848334ab3d19
dependencies:
  required:
    - BuildTools
    - ThirdParty-Glpk
    - ThirdParty-Mumps
    - Data-Sample
    - Data-miplib3
    - CoinUtils
    - Osi
    - Clp
    - Cgl
    - CHiPPS-ALPS
    - CHiPPS-BiCePS
    - CHiPPS-BLIS
    - SYMPHONY
    - Cbc
script: build.sh
