name: pangomm
version: 2.56.1
url: https://download.gnome.org/sources/pangomm/2.56/pangomm-2.56.1.tar.xz
sha256: 539f5aa60e9bdc6b955bb448e2a62cc14562744df690258040fbb74bf885755d
dependencies:
  required:
    - pkg-config
    - cairo
    - cairomm
    - doxygen
    - fribidi
    - glibmm
    - mm-common
    - doxygen
    - libxslt
    - libsigc++
    - pango
    - perl
run: build.bat
