name: uncrustify
version: 0.81.0
url: https://github.com/uncrustify/uncrustify/archive/uncrustify-0.81.0.tar.gz
sha256: 484623dc16b92206adc6ac0770077c6c67c6e441102148c2a121a19549330ff9
steps:
  a:
    dependencies:
    run: build.bat
