name: ruby
version: 3.4.2
url: https://cache.ruby-lang.org/pub/ruby/3.4/ruby-3.4.2.tar.xz
sha256: ebf1c2eb58f5da17c23e965d658dd7e6202c5c50f5179154c5574452bef4b3e0
steps:
  a:
    dependencies:
      - gmp:b
      - libffi
      - openssl
      - yaml
      - zlib
    run: build.bat
