name: ruby
version: 3.4.4
url: https://cache.ruby-lang.org/pub/ruby/3.4/ruby-3.4.4.tar.gz
sha256: a0597bfdf312e010efd1effaa8d7f1d7833146fdc17950caa8158ffa3dcbfa85
steps:
  a:
    dependencies:
      - gmp:b
      - libffi
      - openssl
      - yaml
      - zlib
    run: build.bat
