name: ruby
version: 3.3.6
url: https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.6.tar.xz
steps:
  one:
    dependencies:
      - gmp:two
      - libffi
      - openssl
      - yaml
      - zlib
    run: build.bat