name: ruby
version: 3.4.4
url: https://cache.ruby-lang.org/pub/ruby/3.4/ruby-3.4.4.tar.xz
sha256: f76d63efe9499dedd8526b74365c0c811af00dc9feb0bed7f5356488476e28f4
steps:
  a:
    dependencies:
      - gmp:b
      - libffi
      - openssl
      - yaml
      - zlib
    run: build.bat
