name: nghttp2
version: 1.64.0
url: https://github.com/nghttp2/nghttp2/releases/download/v1.64.0/nghttp2-1.64.0.tar.xz
sha256: 88bb94c9e4fd1c499967f83dece36a78122af7d5fb40da2019c56b9ccc6eb9dd
dependencies:
  required:
    - brotli
    - c-ares
    - libevent
    - libxml2
    - openssl
    - zlib
run: build.bat
