name: nghttp2
version: 1.34.2
url: https://github.com/nghttp2/nghttp2/releases/download/v1.64.0/nghttp2-1.64.0.tar.xz
sha256:
steps:
  a:
    dependencies:
      - brotli
      - c-ares
      - openssl
      - libxml2
      - zlib
    run: build.bat
