name: libass
version: 0.17.3
url: https://github.com/libass/libass/archive/refs/tags/0.17.3.tar.gz
sha256: 26fbfb7a7bd3e6d5c713f8a65a12b36084d1dde6efaed8a9996489054c4aeca0
steps:
  a:
    dependencies:
      - pkg-config
      - libiconv
      - freetype
      - fribidi
      - harfbuzz:b
      - fontconfig
      - libunibreak
    run: build.bat