name: dirent
version: 1.24
url: https://github.com/tronkko/dirent/archive/refs/tags/1.24.tar.gz
sha256: 37009127a65bb1ddc47d06c097321f87f45ca2e998b2ec3bf2e0b2b19649d6f9
steps:
  a:
    dependencies:
    run: build.bat
