name: nettle
version: 3.10
url: https://ftp.gnu.org/gnu/nettle/nettle-3.10.tar.gz
sha256: b4c518adb174e484cb4acea54118f02380c7133771e7e9beb98a0787194ee47c
dependencies:
  required:
    - dlfcn-win32
    - getopt
    - gmp
    - openssl
    - yasm
script: build.sh
