name: gst-plugins-good
version: 1.26.0
url: https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.26.0.tar.xz
sha256: 9e18f139ef69ad0867c2dfbb8fe1d1736d76df11aac83f60e8d3adb1e2eaf03b
steps:
  a:
    dependencies:
      - pkg-config
      - dlfcn-win32
      - gettext
      - glib:b
      - gobject-introspection:b
    run: build.bat
