name: hdf5
version: 1.14.4.3
url: https://github.com/HDFGroup/hdf5/archive/refs/tags/hdf5_1.14.4.3.tar.gz
steps:
  one:
    dependencies:
      - libaec
      - zlib
      - winpthreads
    run: build.bat
