name: a52dec
version: 0.8.0
url: https://distfiles.adelielinux.org/source/a52dec/a52dec-0.8.0.tar.gz
sha256: 03c181ce9c3fe0d2f5130de18dab9bd8bc63c354071515aa56983c74a9cffcc9
steps:
  one:
    dependencies:
      - dlfcn-win32
    run: build.sh
