name: kvazaar
version: 2.3.1
url: https://github.com/ultravideo/kvazaar/archive/refs/tags/v2.3.1.tar.gz
sha256: c5a1699d0bd50bc6bdba485b3438a5681a43d7b2c4fd6311a144740bfa59c9cc
steps:
  one:
    dependencies:
      - getopt
    run: build.bat
