name: libaec
version: 1.1.3
url: https://github.com/MathisRosenhauer/libaec/archive/refs/tags/v1.1.3.tar.gz
sha256: 3669a97e6d8a6b79b708ca43a17233b7267b3c81e26cf26c1d36e12f7d6f4a77
steps:
  a:
    dependencies:
    run: build.bat
