name: z3
version: 4.15.1
url: https://github.com/Z3Prover/z3/archive/refs/tags/z3-4.15.1.tar.gz
sha256: ebf6eed5f2cb217d62abddaa94526189ae40bf3c415fb9c2e2128e099f16fda0
dependencies:
  required:
    - gmp
run: build.bat
