name: HiGHS
version: 1.9.0
url: https://github.com/ERGO-Code/HiGHS/archive/refs/tags/v1.9.0.tar.gz
sha256: dff575df08d88583c109702c7c5c75ff6e51611e6eacca8b5b3fdfba8ecc2cb4
dependencies:
  required:
    - zlib
script: build.bat
