name: rav1e
version: 0.7.1
url: https://github.com/xiph/rav1e/archive/refs/tags/v0.7.1.tar.gz
sha256: da7ae0df2b608e539de5d443c096e109442cdfa6c5e9b4014361211cf61d030c
steps:
  a:
    dependencies:
      - nasm
      - cargo-c
    run: build.bat
