name: rav1e
version: 0.8.1
url: https://github.com/xiph/rav1e/archive/refs/tags/v0.8.1.tar.gz
sha256: 06d1523955fb6ed9cf9992eace772121067cca7e8926988a1ee16492febbe01e
steps:
  a:
    dependencies:
      - nasm
      - cargo-c
    run: build.bat
