name: m4
version: 1.4.19
url: https://ftp.gnu.org/pub/gnu/m4/m4-1.4.19.tar.xz
sha256: 63aede5c6d33b6d9b13511cd0be2cac046f2e70fd0a07aa9573a04a82783af96
steps:
  a:
    dependencies:
      - dirent
      - getopt
      - libiconv
      - libsigsegv
      - gettext
      - winpthreads
    run: build.sh
