name: google-glog
version: 0.7.1
url: https://github.com/google/glog/archive/refs/tags/v0.7.1.tar.gz
sha256: 00e4a87e87b7e7612f519a41e491f16623b12423620006f59f5688bfd8d13b08
dependencies:
  required:
    - dlfcn-win32
script: build.bat
