name: VTK
version: 9.4.2
url: https://www.vtk.org/files/release/9.4/VTK-9.4.2.tar.gz
sha256: 36c98e0da96bb12a30fe53708097aa9492e7b66d5c3b366e1c8dc251e2856a02
dependencies:
  required:
    - freeglut
    - mesa
    - PostgreSQL
    - tcl
    - tk
script: build.bat
