name: leptonica
version: 1.85.0
url: https://github.com/DanBloomberg/leptonica/archive/refs/tags/1.85.0.tar.gz
sha256: c01376bce0379d4ea4bc2ec5d5cbddaa49e2f06f88242619ab8c059e21adf233
dependencies:
  required:
    - giflib
    - libjpeg-turbo
    - libpng
    - libtiff
    - libwebp
    - jbigkit
    - openjpeg
    - xz
    - zlib-ng
    - zstd
script: build.bat
