name: cppcheck
version: 2.18.0
url: https://github.com/danmar/cppcheck/archive/refs/tags/2.18.0.tar.gz
sha256: dc74e300ac59f2ef9f9c05c21d48ae4c8dd1ce17f08914dd30c738ff482e748f
dependencies:
  required:
    - boost
    - libxml2
    - pcre
    - winpthreads
run: build.bat
