name: libgeotiff
version: 1.7.3
url: https://github.com/OSGeo/libgeotiff/archive/refs/tags/1.7.3.tar.gz
sha256: 62eb2cc2f41136bc61b2152ad321fe2e8b3a8ad47794369c685346ea1dc71b1b
steps:
  one:
    dependencies:
      - getopt
      - proj
      - zlib
      - libjpeg-turbo
    run: build.bat
