name: libavif
version: 1.1.1
url: https://github.com/AOMediaCodec/libavif/archive/refs/tags/v1.1.1.tar.gz
sha256: 914662e16245e062ed73f90112fbb4548241300843a7772d8d441bb6859de45b
steps:
  one:
    dependencies:
      - avm
      - dav1d
      - libaom
      - libyuv
      - libgav1
    run: build.bat
