name: libavif
version: 1.2.0
url: https://github.com/AOMediaCodec/libavif/archive/refs/tags/v1.2.0.tar.gz
sha256: 2182f4900d1a9617cee89746922a58dd825f2a3547f23907b8d78dc3685f7d8c
steps:
  a:
    dependencies:
      - avm
      - dav1d
      - libaom
      - libyuv
      - libgav1
      - rav1e
      - SVT-AV1
    run: build.bat
