name: libavif
version: 1.2.1
url: https://github.com/AOMediaCodec/libavif/archive/refs/tags/v1.2.1.tar.gz
sha256: 9c859c7c12ccb0f407511bfe303e6a7247f5f6738f54852662c6df8048daddf4
steps:
  a:
    dependencies:
      - dav1d
      - libaom
      - libyuv
      - libgav1
      - rav1e
      - SVT-AV1
    run: build.bat
