name: libfido2
version: 1.16.0
url: https://developers.yubico.com/libfido2/Releases/libfido2-1.16.0.tar.gz
sha256: 8c2b6fb279b5b42e9ac92ade71832e485852647b53607c43baaafbbcecea04e4
steps:
  a:
    dependencies:
      - libcbor
      - LibreSSL
      - zlib
    run: build.bat
