name: dav1d
version: 1.5.0
url: https://code.videolan.org/videolan/dav1d/-/archive/1.5.0/dav1d-1.5.0.tar.bz2
sha256: a6ca64e34cec56ae1c2d359e1da5c5386ecd7a3a62f931d026ac4f2ff72ade64
dependencies:
  required:
    - pkg-config
    - winpthreads
run: build.bat
