name: gobject-introspection
version: 1.82.0
url: https://gitlab.gnome.org/GNOME/gobject-introspection/-/archive/1.82.0/gobject-introspection-1.82.0.tar.bz2
sha256: f62ecd28fc4d641bcbae47d56fb7328beb1877b4bbdb648424d9b83e9e0496a5
extras:
  - name: gobject-introspection-tests
    version: main
    url: https://gitlab.gnome.org/GNOME/gobject-introspection-tests.git
    recursive: false
    depth: 1
    target: gobject-introspection-tests
dependencies:
  required:
    - pkg-config
    - pcre2
    - glib:required
    - libffi
    - winflexbison
    - zlib
  optional:
    - cairo
script: build.bat
