name: freetype
version: 2.13.2
url: https://download.savannah.gnu.org/releases/freetype/freetype-2.13.2.tar.xz
sha256: 12991c4e55c506dd7f9b765933e62fd2be2e06d421505d7950a132e4f1bb484d
steps:
  a:
    dependencies:
      - brotli
      - bzip2
      - harfbuzz:a
      - libpng
      - zlib
    run: build.bat