name: gp2c
version: 0.0.14
url: https://pari.math.u-bordeaux.fr/pub/pari/GP2C/gp2c-0.0.14.tar.gz
sha256: af6112cc02940457e239da4433d1a0d8da60eeef29f7cc722f64cd4ac00b7b30
dependencies:
  required:
    - pari
    - perl
    - winflexbison
run: build.sh
