name: leveldb
version: 1.23
url: https://github.com/google/leveldb/archive/refs/tags/1.23.tar.gz
sha256: 9a37f8a6174f09bd622bc723b55881dc541cd50747cbd08831c2a82d620f6d76
steps:
  a:
    dependencies:
      - winpthreads
    run: build.bat
