name: superlu
version: 6.0.1
url: https://github.com/xiaoyeli/superlu/archive/refs/tags/v6.0.1.tar.gz
sha256: 6c5a3a9a224cb2658e9da15a6034eed44e45f6963f5a771a6b4562f7afb8f549
steps:
  a:
    dependencies:
      - GKlib
      - METIS
    run: build.bat
