name: vmaf
version: 2.3.1
url: https://github.com/Netflix/vmaf/archive/refs/tags/v2.3.1.tar.gz
sha256: 8d60b1ddab043ada25ff11ced821da6e0c37fd7730dd81c24f1fc12be7293ef2
steps:
  a:
    dependencies:
      - getopt
      - pkg-config
      - llvm-project
      - nasm
      - winpthreads
    run: build.bat
