name: vmaf
version: 3.0.0
url: https://github.com/Netflix/vmaf/archive/refs/tags/v3.0.0.tar.gz
sha256: 7178c4833639e6b989ecae73131d02f70735fdb3fc2c7d84bc36c9c3461d93b1
steps:
  one:
    dependencies:
      - getopt
      - pkg-config
      - nasm
      - winpthreads
    run: build.bat
