#!/bin/bash
#
# NOTICE: don't set PATH_SEPARATOR like below, it will cause issue that 'checking for
# grep that handles long lines and -e... configure: error: no acceptable grep could 
# be found'
# export PATH_SEPARATOR=";"

FWD=`dirname $(pwd)`
CWD=$(cd `dirname $0`; pwd)
PKG_DEPS='suitesparse'
PKG_NAME=eigen
PKG_VER=3.4.0
PKG_URL=https://gitlab.com/libeigen/eigen/-/archive/$PKG_VER/$PKG_NAME-$PKG_VER.tar.bz2
PKGS_DIR=$FWD/pkgs
SRC_DIR=$PKGS_DIR/$PKG_NAME-$PKG_VER
BUILD_DIR=$FWD/out/$PKG_NAME-$PKG_VER

. $FWD/utils/common.sh

clean_build()
{
  echo [$0] Cleaning $PKG_NAME $PKG_VER
  cd $CWD
  if [[ -d "$BUILD_DIR" ]]; then
    if [[ "$BUILD_DIR" != "$SRC_DIR" ]]; then
      rm -rf $BUILD_DIR
    else
      pushd $BUILD_DIR
      ninja clean
      popd
    fi
  fi
}

patch_package()
{
  echo [$0] Patching package $PKG_NAME $PKG_VER
  echo [$0] Nothing to do
}

prepare_package()
{
  clean_build
  clean_log
  create_dirs bin include lib share
  display_info
  download_extract $PKG_URL $PKG_NAME-$PKG_VER.tar.bz2 $PKG_NAME-$PKG_VER
  if [[ ! -d "$BUILD_DIR" ]]; then mkdir -p "$BUILD_DIR"; fi
}

configure_stage()
{
  echo [$0] Configuring $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  configure_options
  # NOTE:
  # 1. Don't install cygwin's cmake because it will use gcc-like compile
  #    command. To use windows's cmake, here have to use 'cygpath -m' to
  #    convert path to windows path but not cygwin path
  # 2. Don't set cmake generator to 'Unix Makefiles' if use MSYS2 shell
  configure_cmd cmake -G "Ninja"                                                                           \
    -DBUILD_SHARED_LIBS=ON                                                                                 \
    -DCMAKE_C_COMPILER=clang-cl                                                                            \
    -DCMAKE_C_FLAGS="-DEIGEN_STRONG_INLINE=inline $OPTIONS $DEFINES -I${PREFIX_PATH_M//;/ -I}"             \
    -DCMAKE_CXX_COMPILER=clang-cl                                                                          \
    -DCMAKE_CXX_FLAGS="-DEIGEN_STRONG_INLINE=inline -EHsc $OPTIONS $DEFINES -I${PREFIX_PATH_M//;/ -I}"     \
    -DCMAKE_BUILD_TYPE=Release                                                                    \
    -DCMAKE_Fortran_COMPILER=flang-new                                                            \
    -DCMAKE_INCLUDE_CURRENT_DIR=ON                                                                \
    -DCMAKE_INSTALL_PREFIX=$PREFIX_M                                                              \
    -DCMAKE_mt=mt                                                                                 \
    -DCMAKE_PREFIX_PATH=$PREFIX_M                                                                 \
    -DCMAKE_POLICY_DEFAULT_CMP0153=OLD                                                            \
    -DINSTALL_PKGCONFIG_DIR="$PREFIX_M/lib/pkgconfig"                                \
    -DEIGEN_BUILD_BTL=ON                                                                          \
    -DEIGEN_CUDA_COMPUTE_ARCH=${NV_COMPUTE//.}                                                    \
    -DEIGEN_TEST_CXX11=ON                                                                         \
    -DEIGEN_TEST_SSE2=ON                                                                          \
    -DEIGEN_TEST_SSE3=ON                                                                          \
    -DEIGEN_TEST_SSSE3=ON                                                                         \
    -DEIGEN_TEST_SSE4_1=ON                                                                        \
    -DEIGEN_TEST_SSE4_2=ON                                                                        \
    -DEIGEN_TEST_AVX=ON                                                                           \
    -DEIGEN_TEST_FMA=ON                                                                           \
    -DEIGEN_TEST_AVX2=ON                                                                          \
    -DEIGEN_TEST_AVX512=ON                                                                        \
    -DEIGEN_TEST_AVX512DQ=ON                                                                      \
    -DEIGEN_TEST_ALTIVEC=ON                                                                       \
    -DEIGEN_TEST_VSX=ON                                                                           \
    -DEIGEN_TEST_MSA=ON                                                                           \
    -DEIGEN_TEST_NEON=ON                                                                          \
    -DEIGEN_TEST_NEON64=ON                                                                        \
    -DEIGEN_TEST_OPENMP=ON                                                                        \
    -DPYTHON_EXECUTABLE="$(python -c 'import sys; print(sys.executable)')"                        \
    $SRC_DIR_M
}

build_stage()
{
  echo [$0] Building $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  build_cmd ninja -j$(nproc)
}

install_package()
{
  echo [$0] Installing $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  install_cmd ninja install
  clean_build
  build_ok
}

process_build()
{
  prepare_package
  configure_stage
  build_stage
  install_package
}

do_actions
