#!/bin/bash
#
# NOTICE: don't set PATH_SEPARATOR like below, it will cause issue that 'checking for
# grep that handles long lines and -e... configure: error: no acceptable grep could 
# be found'
# export PATH_SEPARATOR=";"

FWD=`dirname $(pwd)`
CWD=$(cd `dirname $0`; pwd)
PKG_DEPS=
PKG_NAME=filament
PKG_VER=1.52.2
PKG_URL=https://github.com/google/filament/archive/refs/tags/v$PKG_VER.tar.gz
PKGS_DIR=$FWD/pkgs
SRC_DIR=$PKGS_DIR/$PKG_NAME-$PKG_VER
BUILD_DIR=$FWD/out/$PKG_NAME-$PKG_VER

. $FWD/utils/common.sh

clean_build()
{
  echo [$0] Cleaning $PKG_NAME $PKG_VER
  cd $CWD
  if [[ -d "$BUILD_DIR" ]]; then
    if [[ "$BUILD_DIR" != "$SRC_DIR" ]]; then
      rm -rf $BUILD_DIR
    else
      pushd $BUILD_DIR
      ninja clean
      popd
    fi
  fi
}

patch_package()
{
  echo [$0] Patching package $PKG_NAME $PKG_VER
  echo [$0] Nothing to do
}

prepare_package()
{
  clean_build
  clean_log
  create_dirs bin include lib share
  display_info
  download_extract $PKG_URL $PKG_NAME-$PKG_VER.tar.gz $PKG_NAME-$PKG_VER
  if [[ ! -d "$BUILD_DIR" ]]; then mkdir -p "$BUILD_DIR"; fi
}

configure_stage()
{
  echo [$0] Configuring $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  configure_options
  # NOTE:
  # 1. Don't install cygwin's cmake because it will use gcc-like compile
  #    command. To use windows's cmake, here have to use 'cygpath -m' to
  #    convert path to windows path but not cygwin path
  # 2. Don't set cmake generator to 'Unix Makefiles' if use MSYS2 shell
  # 3. Can't use option BUILD_SHARED_LIBS for filament. some subprojects
  #    under third_party need to be updated to support it, e.g. basisu
  configure_cmd cmake -G "Ninja"                                                     \
    -DCMAKE_BUILD_TYPE=Release                                                       \
    -DCMAKE_C_COMPILER=cl                                                            \
    -DCMAKE_C_FLAGS="$OPTIONS $DEFINES -I${PREFIX_PATH_M//;/ -I}"                    \
    -DCMAKE_CXX_COMPILER=cl                                                          \
    -DCMAKE_CXX_FLAGS="-EHsc $OPTIONS $DEFINES -I${PREFIX_PATH_M//;/ -I}"            \
    -DCMAKE_INSTALL_PREFIX="$PREFIX_M"                                               \
    -DCMAKE_PREFIX_PATH="$PREFIX_PATH_M"                                             \
    -DINSTALL_PKGCONFIG_DIR="$PREFIX_M/lib/pkgconfig"                                \
    -DCMAKE_POLICY_DEFAULT_CMP0148=OLD                                               \
    -DDIST_DIR=""                                                                    \
    -DFILAMENT_WINDOWS_CI_BUILD=ON                                                   \
    -DFILAMENT_SUPPORTS_VULKAN=ON                                                    \
    -DSPIRV_TOOLS_BUILD_STATIC=OFF                                                   \
    -DUSE_STATIC_CRT=OFF                                                             \
    $SRC_DIR_M
}

build_stage()
{
  echo [$0] Building $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  build_cmd ninja -j$(nproc)
}

install_package()
{
  echo [$0] Installing $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  install_cmd ninja install
  if [[ ! -d "$PREFIX/share/doc/$PKG_NAME" ]]; then
    mkdir -p "$PREFIX/share/doc/$PKG_NAME"
  fi
  install_cmd cp -rv $PREFIX/docs/* "$PREFIX/share/doc/$PKG_NAME"
  rm -rfv "$PREFIX/docs"
  install_cmd cp -rv $PREFIX/lib/x86_64/*.lib "$PREFIX/lib"
  rm -rfv "$PREFIX/lib/x86_64"
  install_cmd mv "$PREFIX/LICENSE" "$PREFIX/share/doc/filament/LICENSE"
  install_cmd mv "$PREFIX/README.md" "$PREFIX/share/doc/filament/README.md"
  clean_build
  build_ok
}

process_build()
{
  prepare_package
  configure_stage
  build_stage
  install_package
}

do_actions
