#!/bin/bash
#
# NOTICE: don't set PATH_SEPARATOR like below, it will cause issue that 'checking for
# grep that handles long lines and -e... configure: error: no acceptable grep could 
# be found'
# export PATH_SEPARATOR=";"

FWD=`dirname $(pwd)`
CWD=$(cd `dirname $0`; pwd)
PKG_DEPS=
PKG_NAME=gklib
PKG_VER=5.1.1
PKG_URL=https://github.com/KarypisLab/GKlib/archive/refs/tags/METIS-v$PKG_VER-DistDGL-0.5.tar.gz
PKGS_DIR=$FWD/pkgs
SRC_DIR=$PKGS_DIR/$PKG_NAME-$PKG_VER
BUILD_DIR=$FWD/out/$PKG_NAME-$PKG_VER

. $FWD/utils/common.sh

clean_build()
{
  echo [$0] Cleaning $PKG_NAME $PKG_VER
  cd $CWD
  if [[ -d "$BUILD_DIR" ]]; then
    if [[ "$BUILD_DIR" != "$SRC_DIR" ]]; then
      rm -rf $BUILD_DIR
    else
      pushd $BUILD_DIR
      ninja clean
      popd
    fi
  fi
}

patch_package()
{
  echo [$0] Patching package $PKG_NAME $PKG_VER
  pushd $SRC_DIR
  patch -Np1 -i $PATCHES_DIR/001-gklib-5.1.1-fix-compile-error-C2371.diff
  popd
}

prepare_package()
{
  clean_build
  clean_log
  create_dirs bin include lib share
  display_info
  download_extract $PKG_URL $PKG_NAME-$PKG_VER.tar.gz $PKG_NAME-$PKG_VER
  if [ ! -d "$BUILD_DIR" ]; then mkdir -p "$BUILD_DIR"; fi
}

configure_stage()
{
  echo [$0] Configuring $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  array=($(echo $PREFIX_PATH_M | tr ";" "\n"))
  for p in ${array[@]}; do
    local old_include="$p/include"
    if [[ -d "$old_include" ]] && [[ "$INCLUDE" != *"${old_include//\//\\}"* ]]; then
      if [[ -z "$INCLUDE" ]]; then
        INCLUDE=$(win_wpath "$old_include")
      else
        INCLUDE="$INCLUDE"';'$(win_wpath "$old_include")
      fi
    fi
    local old_lib="$p/lib"
    if [[ -d "$old_lib" ]] && [[ "$LIB" != *"${old_lib//\//\\}"* ]]; then
      if [[ -z "$LIB" ]]; then
        LIB=$(win_wpath "$old_lib")
      else
        LIB="$LIB"';'$(win_wpath "$old_lib")
      fi
    fi
  done
  OPTIONS='-nologo -MD -fp:precise -diagnostics:column -wd4819 -openmp:llvm'
  DEFINES="-DWIN32 -D_WIN32_WINNT=$WIN32_TARGET -D_CRT_DECLARE_NONSTDC_NAMES -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE"
  # NOTE:
  # 1. Don't install cygwin's cmake because it will use gcc-like compile
  #    command. To use windows's cmake, here have to use 'cygpath -m' to
  #    convert path to windows path but not cygwin path
  # 2. Don't set cmake generator to 'Unix Makefiles' if use MSYS2 shell
  # TODO: Fail if use '-DBUILD_SHARED_LIBS=ON'
  configure_cmd cmake -G "Ninja"                                                     \
    -DCMAKE_BUILD_TYPE=Release                                                       \
    -DCMAKE_C_COMPILER=cl                                                            \
    -DCMAKE_C_FLAGS="$OPTIONS $DEFINES $INCLUDES"                                    \
    -DCMAKE_CXX_COMPILER=cl                                                          \
    -DCMAKE_CXX_FLAGS="-EHsc $OPTIONS $DEFINES $INCLUDES"                            \
    -DCMAKE_INSTALL_PREFIX="$PREFIX_M"                                               \
    -DCMAKE_PREFIX_PATH="$PREFIX_PATH_M"                                             \
    -DOPENMP=ON                                                                      \
    -DGKREGEX=ON                                                                     \
    -DGKRAND=ON                                                                      \
    $SRC_DIR_M
}

build_stage()
{
  echo [$0] Building $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  build_cmd ninja -j$(nproc)
}

install_package()
{
  echo [$0] Installing $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  install_cmd ninja install
  clean_build
  build_ok
}

process_build()
{
  prepare_package
  configure_stage
  build_stage
  install_package
}

do_actions
