#!/bin/bash
#
# NOTICE: don't set PATH_SEPARATOR like below, it will cause issue that 'checking for
# grep that handles long lines and -e... configure: error: no acceptable grep could 
# be found'
# export PATH_SEPARATOR=";"

FWD=`dirname $(pwd)`
CWD=$(cd `dirname $0`; pwd)
PKG_DEPS='abseil-cpp c-ares re2 openssl zlib'
PKG_NAME=grpc
PKG_VER=1.66.1
# NOTE: Don't use archive but git for grpc. Because archive was missing files during
#       build
PKG_URL=https://github.com/grpc/$PKG_NAME.git
PKGS_DIR=$FWD/pkgs
SRC_DIR=$PKGS_DIR/$PKG_NAME
BUILD_DIR=$FWD/out/$PKG_NAME

. $FWD/utils/common.sh

clean_build()
{
  echo [$0] Cleaning $PKG_NAME $PKG_VER
  cd $CWD
  if [[ -d "$BUILD_DIR" ]]; then
    if [[ "$BUILD_DIR" != "$SRC_DIR" ]]; then
      rm -rf $BUILD_DIR
    else
      pushd $BUILD_DIR
      ninja clean
      popd
    fi
  fi
}

patch_package()
{
  echo [$0] Patching package $PKG_NAME $PKG_VER
  echo [$0] Nothing to do
}

prepare_package()
{
  clean_build
  clean_log
  create_dirs bin include lib share
  display_info
  git_rescure v$PKG_VER
  if [[ ! -d "$BUILD_DIR" ]]; then mkdir -p "$BUILD_DIR"; fi
}

configure_stage()
{
  echo [$0] Configuring $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  configure_options
  # NOTE:
  # 1. Don't install cygwin's cmake because it will use gcc-like compile
  #    command. To use windows's cmake, here have to use 'cygpath -m' to
  #    convert path to windows path but not cygwin path
  # 2. Don't set cmake generator to 'Unix Makefiles' if use MSYS2 shell
  # 3. Don't build protobuf standalone and use grpc's one. because it may
  #    have version conflict with upb header files and cause grpc build failed
  # 4. Don't set '-DBUILD_SHARED_LIBS=ON', it will cause upb build fail for 
  #    this package
  configure_cmd cmake -G "Ninja"                                                     \
    -DCMAKE_BUILD_TYPE=Release                                                       \
    -DCMAKE_C_COMPILER=cl                                                            \
    -DCMAKE_C_FLAGS="$OPTIONS $DEFINES -I${PREFIX_PATH_M//;/ -I}"                    \
    -DCMAKE_CXX_COMPILER=cl                                                          \
    -DCMAKE_CXX_FLAGS="-EHsc $OPTIONS $DEFINES -I${PREFIX_PATH_M//;/ -I}"            \
    -DCMAKE_INSTALL_PREFIX="$PREFIX_M"                                               \
    -DCMAKE_PREFIX_PATH="$PREFIX_PATH_M"                                             \
    -DgRPC_INSTALL=ON                                                                \
    -DgRPC_ABSL_PROVIDER=package                                                     \
    -DgRPC_CARES_PROVIDER=package                                                    \
    -DgRPC_RE2_PROVIDER=package                                                      \
    -DgRPC_SSL_PROVIDER=package                                                      \
    -DgRPC_ZLIB_PROVIDER=package                                                     \
    $SRC_DIR_M
}

build_stage()
{
  echo [$0] Building $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  build_cmd ninja -j$(nproc)
}

install_package()
{
  echo [$0] Installing $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  install_cmd ninja install
  clean_build
  build_ok
}

process_build()
{
  prepare_package
  configure_stage
  build_stage
  install_package
}

do_actions
