#!/bin/bash
#
# NOTICE: don't set PATH_SEPARATOR like below, it will cause issue that 'checking for
# grep that handles long lines and -e... configure: error: no acceptable grep could 
# be found'
# export PATH_SEPARATOR=";"

FWD=`dirname $(pwd)`
CWD=$(cd `dirname $0`; pwd)
PKG_DEPS=
PKG_NAME=icu4c
PKG_VER=75_1
# NOTE:
# 1. Don't use the archive, it is missing the file '$srcdir/data/locales/root.txt'.
#    It will cause the content of data/rules.mk is empty, so that will throw out the
#    error: no rule to make target "out/tmp/dirs.timestamp" needed by "out/tmp/icudata.res"
PKG_URL=https://github.com/unicode-org/icu/releases/download/release-${PKG_VER//_/-}/$PKG_NAME-$PKG_VER-src.tgz
PKGS_DIR=$FWD/pkgs
SRC_DIR=$PKGS_DIR/$PKG_NAME-$PKG_VER
# NOTE:
# 1. Make the root of build directories and source directories are exactly the same.
#    Otherwise cygwin path will cause most header files can't be found during compiling
BUILD_DIR=$SRC_DIR

. $FWD/utils/common.sh

clean_build()
{
  echo [$0] Cleaning $PKG_NAME $PKG_VER
  cd $CWD
  if [[ -d "$BUILD_DIR" ]]; then
    if [[ "$BUILD_DIR" != "$SRC_DIR" ]]; then
      rm -rf $BUILD_DIR
    else
      pushd $BUILD_DIR
        rm -rf bin${ARCH/x/} include lib${ARCH/x/}
      popd
    fi
  fi
}

patch_package()
{
  echo [$0] Patching package $PKG_NAME $PKG_VER
  echo [$0] Nothing to do
}

prepare_package()
{
  clean_build
  clean_log
  create_dirs bin include lib share
  display_info
  download_extract $PKG_URL $PKG_NAME-$PKG_VER.tar.tgz $PKG_NAME-$PKG_VER
  if [[ ! -d "$BUILD_DIR" ]]; then mkdir -p "$BUILD_DIR"; fi
}

configure_stage()
{
  echo [$0] Configuring $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  configure_options
}

build_stage()
{
  echo [$0] Building $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  build_cmd cmd /c "msbuild source/allinone/allinone.sln /p:Configuration=Release /p:Platform=x64 /p:SkipUWP=true"
}

install_package()
{
  echo [$0] Installing $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  install_cmd cp -rv bin${ARCH/x/}/*.* $PREFIX_M/bin
  install_cmd cp -rv include/unicode $PREFIX_M/include
  install_cmd cp -rv lib${ARCH/x/}/*.lib $PREFIX_M/lib
  clean_build
  build_ok icu
}

process_build()
{
  prepare_package
  configure_stage
  build_stage
  install_package
}

do_actions icu
