#!/bin/bash
#
# NOTICE: don't set PATH_SEPARATOR like below, it will cause issue that 'checking for
# grep that handles long lines and -e... configure: error: no acceptable grep could 
# be found'
# export PATH_SEPARATOR=";"

FWD=`dirname $(pwd)`
CWD=$(cd `dirname $0`; pwd)
PKG_DEPS='libiconv'
PKG_NAME=libsigsegv
PKG_VER=2.14
PKG_URL=https://ftp.gnu.org/pub/gnu/$PKG_NAME/$PKG_NAME-$PKG_VER.tar.gz
PKGS_DIR=$FWD/pkgs
SRC_DIR=$PKGS_DIR/$PKG_NAME-$PKG_VER
BUILD_DIR=$FWD/out/$PKG_NAME-$PKG_VER

. $FWD/utils/common.sh

clean_build()
{
  echo [$0] Cleaning $PKG_NAME $PKG_VER
  cd $CWD
  if [ -d "$BUILD_DIR" ]; then
    if [ "$BUILD_DIR" != "$SRC_DIR" ]; then
      rm -rf $BUILD_DIR
    else
      pushd $BUILD_DIR
      make distclean
      popd
    fi
  fi
}

patch_package()
{
  echo [$0] Patching package $PKG_NAME $PKG_VER
  pushd $SRC_DIR
  patch -Np1 -i $PATCHES_DIR/001-libsigsegv-2.14-not-a-member-of-context.diff

  # XXX: libtool don't have options can set the naming style of static and 
  #      shared library. Here is only a workaround.
  echo [$0] Patching ltmain.sh in build-aux
  pushd build-aux
  sed                                                                                                \
    -e "s|old_library='\$old_library'|old_library='lib\$old_library'|g"                              \
    -e 's|oldlibs="$output_objdir/$libname.$libext|oldlibs="$output_objdir/lib$libname.$libext|g'    \
    -e 's|oldlibs " $output_objdir/$libname.$libext|oldlibs " $output_objdir/lib$libname.$libext|g'  \
    ltmain.sh > ltmain.sh-t
  mv ltmain.sh-t ltmain.sh
  popd

  echo [$0] Patching configure in top level
  sed                                                                                                \
    -e "s|library_names_spec='\$libname.dll.lib'|library_names_spec='\$libname.lib'|g"               \
    -e 's|$tool_output_objdir$libname.dll.lib|$tool_output_objdir$libname.lib|g'                     \
    configure > configure-t
  mv configure-t configure
  chmod +x configure
  popd
}

prepare_package()
{
  clean_build
  clean_log
  create_dirs bin include lib share
  display_info
  download_extract $PKG_URL $PKG_NAME-$PKG_VER.tar.gz $PKG_NAME-$PKG_VER
  if [ ! -d "$BUILD_DIR" ]; then mkdir -p "$BUILD_DIR"; fi
}

configure_stage()
{
  echo [$0] Configuring $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  array=($(echo $PREFIX_PATH_M | tr ";" "\n"))
  for p in ${array[@]}; do
    local old_lib="$p/lib"
    if [[ -d "$old_lib" ]] && [[ "$LDFLAGS" != *"$old_lib"* ]]; then
      if [ -z "$LDFLAGS" ]; then
        LDFLAGS='-L'"$p"'/lib'
      else
        LDFLAGS="$LDFLAGS"' -L'"$p"'/lib'
      fi
    fi
  done
  OPTIONS='-nologo -MD -fp:precise -diagnostics:column -wd4819 -openmp:llvm'
  DEFINES="-DWIN32 -D_WIN32_WINNT=$WIN32_TARGET -D_CRT_DECLARE_NONSTDC_NAMES -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS"
  # NOTE:
  # 1. Don't use CPP="$FWD/wrapper/compile cl -nologo -EP" here,
  #    it will cause checking absolute name of standard files is empty.
  #    e.g. checking absolute name of <fcntl.h> ... '', but we can use
  #    CPP="$FWD/wrapper/compile cl -nologo -E" 
  # 2. Don't use 'compile cl -nologo' but 'compile cl'. Because configure 
  #    on some libraries will detect whether is msvc compiler according to
  #    '*cl | cl.exe'
  configure_cmd $SRC_DIR/configure --build=$BUILD_TRIPLET                                      \
    --host=$HOST_TRIPLET                                                                       \
    --prefix="$PREFIX"                                                                         \
    --libdir="$PREFIX/lib"                                                                     \
    --mandir="$PREFIX/share/man"                                                               \
    --enable-static                                                                            \
    --enable-shared                                                                            \
    --enable-relocatable                                                                       \
    AR="$FWD/wrapper/ar-lib lib -nologo"                                                       \
    CC="$FWD/wrapper/compile cl"                                                               \
    CFLAGS="$OPTIONS"                                                                          \
    CPP="$FWD/wrapper/compile cl -E"                                                           \
    CPPFLAGS="$DEFINES $INCLUDES"                                                              \
    CXX="$FWD/wrapper/compile cl"                                                              \
    CXXFLAGS="-EHsc $OPTIONS"                                                                  \
    DLLTOOL='link.exe -verbose -dll'                                                           \
    LD="link -nologo"                                                                          \
    LDFLAGS="$LDFLAGS"                                                                         \
    NM="dumpbin -nologo -symbols"                                                              \
    RANLIB=":"                                                                                 \
    RC="$FWD/wrapper/windres-rc rc -nologo"                                                    \
    STRIP=":"                                                                                  \
    WINDRES="$FWD/wrapper/windres-rc rc -nologo"                                               \
    gt_cv_locale_zh_CN=none
}

build_stage()
{
  echo [$0] Building $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  build_cmd make -j$(nproc)
}

install_package()
{
  echo [$0] Installing $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  install_cmd make install
  clean_build
  build_ok
}

process_build()
{
  prepare_package
  configure_stage
  build_stage
  install_package
}

do_actions
