#!/bin/bash
#
# NOTICE: don't set PATH_SEPARATOR like below, it will cause issue that 'checking for
# grep that handles long lines and -e... configure: error: no acceptable grep could 
# be found'
# export PATH_SEPARATOR=";"

FWD=`dirname $(pwd)`
CWD=$(cd `dirname $0`; pwd)
PKG_DEPS=
PKG_NAME=libvpx
PKG_VER=1.14.1
PKG_URL=https://github.com/webmproject/libvpx/archive/refs/tags/v$PKG_VER.tar.gz
PKGS_DIR=$FWD/pkgs
SRC_DIR=$PKGS_DIR/$PKG_NAME-$PKG_VER
BUILD_DIR=$FWD/out/$PKG_NAME-$PKG_VER

. $FWD/utils/common.sh

clean_build()
{
  echo [$0] Cleaning $PKG_NAME $PKG_VER
  cd $CWD
  if [[ -d "$BUILD_DIR" ]]; then
    if [[ "$BUILD_DIR" != "$SRC_DIR" ]]; then
      rm -rf $BUILD_DIR
    else
      pushd $BUILD_DIR
      make distclean
      popd
    fi
  fi
}

patch_package()
{
  echo [$0] Patching package $PKG_NAME $PKG_VER
  echo [$0] Nothing to do
}

prepare_package()
{
  clean_build
  clean_log
  create_dirs bin include lib share
  display_info
  download_extract $PKG_URL $PKG_NAME-$PKG_VER.tar.gz $PKG_NAME-$PKG_VER
  if [[ ! -d "$BUILD_DIR" ]]; then mkdir -p "$BUILD_DIR"; fi
}

configure_stage()
{
  echo [$0] Configuring $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  configure_options
  if [[ "$ARCH" == "x86" ]]; then
    HOST_TRIPLET=x86-win32-vs17
  else
    HOST_TRIPLET=x86_64-win64-vs17
  fi
  # NOTE:
  # 1. Don't use CPP="$FWD/wrapper/compile cl -nologo -EP" here,
  #    it will cause checking absolute name of standard files is empty.
  #    e.g. checking absolute name of <fcntl.h> ... '', but we can use
  #    CPP="$FWD/wrapper/compile cl -nologo -E" 
  # 2. Don't use 'compile cl -nologo' but 'compile cl'. Because configure 
  #    on some libraries will detect whether is msvc compiler according to
  #    '*cl | cl.exe'
  configure_cmd $SRC_DIR/configure                                   \
    --target=$HOST_TRIPLET                                           \
    --prefix="$PREFIX"                                               \
    --disable-examples                                               \
    --disable-docs                                                   \
    --enable-vp8                                                     \
    --enable-vp9                                                     \
    --enable-postproc                                                \
    --enable-vp9-postproc                                            \
    --enable-onthefly-bitpacking                                     \
    --enable-error-concealment                                       \
    --enable-coefficient-range-checking                              \
    --enable-runtime-cpu-detect                                      \
    --enable-static                                                  \
    --enable-small                                                   \
    --enable-postproc-visualizer                                     \
    --enable-multi-res-encoding                                      \
    --enable-vp9-temporal-denoising                                  \
    --enable-webm-io                                                 \
    --enable-libyuv
}

build_stage()
{
  echo [$0] Building $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  build_cmd make -j$(nproc)
}

install_package()
{
  echo [$0] Installing $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  install_cmd make install
  clean_build
  build_ok
}

process_build()
{
  prepare_package
  configure_stage
  build_stage
  install_package
}

do_actions
