#!/bin/bash
#
# NOTICE: don't set PATH_SEPARATOR like below, it will cause issue that 'checking for
# grep that handles long lines and -e... configure: error: no acceptable grep could 
# be found'
# export PATH_SEPARATOR=";"

FWD=`dirname $(pwd)`
CWD=$(cd `dirname $0`; pwd)
PKG_DEPS='cpp-httplib libffi libxml2 lua perl xz zlib zstd'
PKG_NAME=llvm-project
PKG_VER=18.1.8
PKG_URL=https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-$PKG_VER.tar.gz
PKGS_DIR=$FWD/pkgs
SRC_DIR=$PKGS_DIR/$PKG_NAME-$PKG_VER
BUILD_DIR=$FWD/out/$PKG_NAME-$PKG_VER

. $FWD/utils/common.sh

clean_build()
{
  echo [$0] Cleaning $PKG_NAME $PKG_VER
  cd $CWD
  if [[ -d "$BUILD_DIR" ]]; then
    if [[ "$BUILD_DIR" != "$SRC_DIR" ]]; then
      rm -rf $BUILD_DIR
    else
      pushd $BUILD_DIR
      ninja clean
      popd
    fi
  fi
}

patch_package()
{
  echo [$0] Patching package $PKG_NAME $PKG_VER
  pushd $SRC_DIR/llvm/cmake
  patch -Np1 -i $PATCHES_DIR/001-llvm-project-18.1.8-fix-cmake-error-if-can-not-find-zstd-target.diff
  popd
  pushd $SRC_DIR/llvm/utils
  patch -Np0 -i $PATCHES_DIR/002-llvm-project-18.1.8-fix-SyntaxWarning-invalid-escape-sequence-if-use-python-3.12.diff
  popd
}

prepare_package()
{
  clean_build
  clean_log
  create_dirs bin include lib
  display_info
  download_extract $PKG_URL $PKG_NAME-$PKG_VER.tar.gz $PKG_NAME-$PKG_VER
  if [[ ! -d "$BUILD_DIR" ]]; then mkdir -p "$BUILD_DIR"; fi
}

configure_stage()
{
  echo [$0] Configuring $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  configure_options
  bootstrap_cmake_options='CMAKE_BUILD_TYP;CMAKE_INSTALL_PREFI;CMAKE_PREFIX_PAT;CMAKE_POLICY_DEFAULT_CMP007;CMAKE_POLICY_DEFAULT_CMP011;CMAKE_POLICY_DEFAULT_CMP011;CLANG_DEFAULT_CXX_STDLI;CLANG_DEFAULT_RTLI;CLANG_INCLUDE_DOC;LLVM_BUILD_DOC;LLVM_BUILD_EXAMPLE;LLVM_BUILD_TEST;LLVM_BUILD_TOOL;LLVM_BUILD_UTIL;LLVM_BUILD_LLVM_C_DYLI;LLVM_ENABLE_DOXYGE;LLVM_ENABLE_OCAMLDO;LLVM_ENABLE_PLUGIN;LLVM_EXPORT_SYMBOLS_FOR_PLUGIN;LLVM_INCLUDE_DOC;LLVM_INCLUDE_EXAMPLE;LLVM_INCLUDE_TEST;LLVM_INCLUDE_TOOL;LLVM_INCLUDE_UTIL;LLVM_INSTALL_UTIL;LLVM_ENABLE_PROJECT;LLVM_ENABLE_RUNTIME;LLVM_ENABLE_RTT;LLVM_RUNTIME_TARGET;LLVM_OPTIMIZED_TABLEGE;LLVM_TARGETS_TO_BUIL;LIBCXX_USE_COMPILER_R;Python3_EXECUTABLE'
  bootstrap_cmake_cxx_flags='-Xclang -O3 -march=native -fms-extensions -fms-compatibility -fms-compatibility-version=19.41'
  # NOTE:
  # 1. Don't install cygwin's cmake because it will use gcc-like compile
  #    command. To use windows's cmake, here have to use 'cygpath -m' to
  #    convert path to windows path but not cygwin path
  # 2. Don't set cmake generator to 'Unix Makefiles' if use MSYS2 shell
  configure_cmd cmake -G "Ninja"                                                                         \
    -DBOOTSTRAP_CMAKE_CXX_FLAGS="$bootstrap_cmake_cxx_flags $OPTIONS $DEFINES -I${PREFIX_PATH_M//;/ -I}" \
    -DCMAKE_BUILD_TYPE=Release                                                                           \
    -DCMAKE_C_COMPILER=cl                                                                                \
    -DCMAKE_C_FLAGS="${OPTIONS//-MD /} $DEFINES -I${PREFIX_PATH_M//;/ -I}"                               \
    -DCMAKE_CXX_COMPILER=cl                                                                              \
    -DCMAKE_CXX_FLAGS="${OPTIONS//-MD /} $DEFINES -I${PREFIX_PATH_M//;/ -I}"                             \
    -DCMAKE_INSTALL_PREFIX="$PREFIX_M"                                                                   \
    -DCMAKE_PREFIX_PATH="$PREFIX_PATH_M"                                                                 \
    -DCMAKE_POLICY_DEFAULT_CMP0076=OLD                                                                   \
    -DCMAKE_POLICY_DEFAULT_CMP0114=OLD                                                                   \
    -DCMAKE_POLICY_DEFAULT_CMP0116=OLD                                                                   \
    -DCLANG_DEFAULT_CXX_STDLIB=libc++                                                                    \
    -DCLANG_DEFAULT_RTLIB=compiler-rt                                                                    \
    -DCLANG_INCLUDE_DOCS=OFF                                                                             \
    -DLLVM_BUILD_DOCS=OFF                                                                                \
    -DLLVM_BUILD_EXAMPLES=OFF                                                                            \
    -DLLVM_BUILD_TESTS=OFF                                                                               \
    -DLLVM_BUILD_TOOLS=ON                                                                                \
    -DLLVM_BUILD_UTILS=ON                                                                                \
    -DLLVM_BUILD_LLVM_C_DYLIB=ON                                                                         \
    -DLLVM_ENABLE_DOXYGEN=OFF                                                                            \
    -DLLVM_ENABLE_OCAMLDOC=OFF                                                                           \
    -DLLVM_ENABLE_PLUGINS=ON                                                                             \
    -DLLVM_ENABLE_PROJECTS="bolt;clang;clang-tools-extr;flang;mlir;ll;pstl;polly"                        \
    -DLLVM_ENABLE_RUNTIMES="compiler-rt;libcxx;openmp"                                                   \
    -DLLVM_ENABLE_RTTI=ON                                                                                \
    -DLLVM_EXPORT_SYMBOLS_FOR_PLUGINS=ON                                                                 \
    -DLLVM_INCLUDE_DOCS=OFF                                                                              \
    -DLLVM_INCLUDE_EXAMPLES=OFF                                                                          \
    -DLLVM_INCLUDE_TESTS=OFF                                                                             \
    -DLLVM_INCLUDE_TOOLS=ON                                                                              \
    -DLLVM_INCLUDE_UTILS=ON                                                                              \
    -DLLVM_INSTALL_UTILS=ON                                                                              \
    -DLLVM_OPTIMIZED_TABLEGEN=ON                                                                         \
    -DLLVM_TARGETS_TO_BUILD=X86                                                                          \
    -DLIBCXX_USE_COMPILER_RT=ON                                                                          \
    -DPython3_EXECUTABLE="$(python -c 'import sys; print(sys.executable)')"                              \
    -DCLANG_ENABLE_BOOTSTRAP=ON                                                                          \
    -DCLANG_BOOTSTRAP_PASSTHROUGH="$bootstrap_cmake_options"                                             \
    "$SRC_DIR_M/llvm"
}

build_stage()
{
  echo [$0] Building $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  build_cmd ninja -j$(nproc) stage2
}

install_package()
{
  echo [$0] Installing $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  install_cmd ninja -j$(nproc) stage2-install
  clean_build
  build_ok
}

process_build()
{
  prepare_package
  configure_stage
  build_stage
  install_package
}

do_actions
