#!/bin/bash
#
# NOTICE: don't set PATH_SEPARATOR like below, it will cause issue that 'checking for
# grep that handles long lines and -e... configure: error: no acceptable grep could 
# be found'
# export PATH_SEPARATOR=";"

FWD=`dirname $(pwd)`
CWD=$(cd `dirname $0`; pwd)
PKG_DEPS=
PKG_NAME=lua
PKG_VER=5.4.6
PKG_URL=https://www.lua.org/ftp/$PKG_NAME-$PKG_VER.tar.gz
PKGS_DIR=$FWD/pkgs
SRC_DIR=$PKGS_DIR/$PKG_NAME-$PKG_VER
BUILD_DIR=$SRC_DIR/src

. $FWD/utils/common.sh

clean_build()
{
  echo [$0] Cleaning $PKG_NAME $PKG_VER
  cd $CWD
  if [[ -d "$BUILD_DIR" ]]; then
    if [[ "$BUILD_DIR" != "$SRC_DIR" ]]; then
      rm -rf $BUILD_DIR
    else
      pushd $BUILD_DIR
      rm -rfv *.o *.obj *.exp *.lib *.dll *.exe
      popd
    fi
  fi
}

prepare_package()
{
  clean_build
  clean_log
  create_dirs bin include lib
  display_info
  download_extract $PKG_URL $PKG_NAME-$PKG_VER.tar.gz $PKG_NAME-$PKG_VER
  if [[ ! -d "$BUILD_DIR" ]]; then mkdir -p "$BUILD_DIR"; fi
}

configure_stage()
{
  echo [$0] Configuring $PKG_NAME $PKG_VER
  cd $SRC_DIR
  configure_options
}

build_stage()
{
  echo [$0] Building $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  local pkg_ver_trim=`echo ${PKG_VER%.*} | awk -F "." '{print $1 $2}'`
  local all_obj=$(ls *.c)
  local base_obj=`echo $all_obj | sed -e 's|lua[a-z]*.c\s*||g'`
  # modified from https://blog.spreendigital.de/2020/05/21/how-to-compile-lua-5-4-0-for-windows/
  build_cmd cl /nologo /MD /O2 /c /DLUA_COMPAT_5_3 /DLUA_BUILD_AS_DLL /D_CRT_DECLARE_NONSTDC_NAMES /D_CRT_NONSTDC_NO_DEPRECATE *.c
  build_cmd link /NOLOGO /DLL /IMPLIB:lua.lib /OUT:lua$pkg_ver_trim.dll ${base_obj//.c/.obj}
  build_cmd link /NOLOGO /OUT:lua.exe lua.obj lua.lib
  build_cmd lib /OUT:liblua.lib ${base_obj//.c/.obj}
  build_cmd link /NOLOGO /OUT:luac.exe luac.obj liblua.lib
}

install_package()
{
  echo [$0] Installing $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  install_cmd cp -rv *.exe $PREFIX/bin
  install_cmd cp -rv *.lib $PREFIX/lib
  install_cmd cp -rv *.dll $PREFIX/bin
  install_cmd cp -rv lauxlib.h $PREFIX/include
  install_cmd cp -rv lua*.h $PREFIX/include
  install_cmd cp -rv lua*.hpp $PREFIX/include
  clean_build
  build_ok
}

process_build()
{
  prepare_package
  configure_stage
  build_stage
  install_package
}

do_actions
