#!/bin/bash
#
# NOTICE: don't set PATH_SEPARATOR like below, it will cause issue that 'checking for
# grep that handles long lines and -e... configure: error: no acceptable grep could 
# be found'
# export PATH_SEPARATOR=";"

FWD=`dirname $(pwd)`
CWD=$(cd `dirname $0`; pwd)
PKG_DEPS='gmp mpfr yasm'
PKG_NAME=mpc
PKG_VER=1.3.1
PKG_URL=https://ftp.gnu.org/gnu/mpc/$PKG_NAME-$PKG_VER.tar.gz
PKGS_DIR=$FWD/pkgs
SRC_DIR=$PKGS_DIR/$PKG_NAME-$PKG_VER
BUILD_DIR=$FWD/out/$PKG_NAME-$PKG_VER

. $FWD/utils/common.sh

clean_build()
{
  echo [$0] Cleaning $PKG_NAME $PKG_VER
  cd $CWD
  if [[ -d "$BUILD_DIR" ]]; then
    if [[ "$BUILD_DIR" != "$SRC_DIR" ]]; then
      rm -rf $BUILD_DIR
    else
      pushd $BUILD_DIR
      make distclean
      popd
    fi
  fi
}

patch_package()
{
  echo [$0] Patching package $PKG_NAME $PKG_VER
  pushd $SRC_DIR

  # NOTE: 
  # 1. mpfr only can build static or shared library but not both together, so that don't
  #    patch ltmain.sh to change the name of library
  # XXX: libtool don't have options can set the naming style of static and 
  #      shared library. Here is only a workaround.
  # echo [$0] Patching ltmain.sh at build-aux
  # pushd build-aux
  # sed                                                                                                \
  #   -e "s|old_library='\$old_library'|old_library='lib\$old_library'|g"                              \
  #   -e 's|oldlibs="$output_objdir/$libname.$libext|oldlibs="$output_objdir/lib$libname.$libext|g'    \
  #   -e 's|oldlibs " $output_objdir/$libname.$libext|oldlibs " $output_objdir/lib$libname.$libext|g'  \
  #   ltmain.sh > ltmain.sh-t
  # mv ltmain.sh-t ltmain.sh
  # popd

  echo [$0] Patching configure in top level
  sed                                                                                                \
    -e "s|library_names_spec='\$libname.dll.lib'|library_names_spec='\$libname.lib'|g"               \
    -e 's|$tool_output_objdir$libname.dll.lib|$tool_output_objdir$libname.lib|g'                     \
    configure > configure-t
  mv configure-t configure
  chmod +x configure
  popd
}

prepare_package()
{
  clean_build
  clean_log
  create_dirs bin include lib share
  display_info
  download_extract $PKG_URL $PKG_NAME-$PKG_VER.tar.gz $PKG_NAME-$PKG_VER
  if [[ ! -d "$BUILD_DIR" ]]; then mkdir -p "$BUILD_DIR"; fi
}

configure_stage()
{
  echo [$0] Configuring $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  configure_options
  # NOTE:
  # 1. Don't use CPP="$FWD/wrapper/compile cl -nologo -EP" here,
  #    it will cause checking absolute name of standard files is empty.
  #    e.g. checking absolute name of <fcntl.h> ... '', but we can use
  #    CPP="$FWD/wrapper/compile cl -nologo -E" 
  # 2. Don't use 'compile cl -nologo' but 'compile cl'. Because configure 
  #    on some libraries will detect whether is msvc compiler according to
  #    '*cl | cl.exe'
  configure_cmd $SRC_DIR/configure --build=$BUILD_TRIPLET                            \
    --host=$HOST_TRIPLET                                                             \
    --prefix="$PREFIX"                                                               \
    --libdir="$PREFIX/lib"                                                           \
    --mandir="$PREFIX/share/man"                                                     \
    --enable-static                                                                  \
    --disable-shared                                                                 \
    --with-gmp=$GMP_PREFIX                                                           \
    --with-mpfr=$MPFR_PREFIX                                                         \
    AR="$FWD/wrapper/ar-lib lib -nologo"                                             \
    AS="yasm -Xvc -f $YASM_OBJ_FMT -rraw -pgas"                                      \
    CC="$FWD/wrapper/compile cl"                                                     \
    CFLAGS="$OPTIONS"                                                                \
    CPP="$FWD/wrapper/compile cl -E"                                                 \
    CPPFLAGS="$DEFINES -I${PREFIX_PATH_M//;/ -I}"                                    \
    CXX="$FWD/wrapper/compile cl"                                                    \
    CXXFLAGS="-EHsc $OPTIONS"                                                        \
    DLLTOOL='link.exe -verbose -dll'                                                 \
    LD="link -nologo"                                                                \
    LDFLAGS="-L${PREFIX_PATH_M//;/ -L}"                                              \
    NM="dumpbin -nologo -symbols"                                                    \
    RANLIB=":"                                                                       \
    RC="$FWD/wrapper/windres-rc rc -nologo"                                          \
    STRIP=":"                                                                        \
    WINDRES="$FWD/wrapper/windres-rc rc -nologo"                                     \
    gt_cv_locale_zh_CN=none
}

build_stage()
{
  echo [$0] Building $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  build_cmd make -j$(nproc)
}

install_package()
{
  echo [$0] Installing $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  install_cmd make install
  clean_build
  build_ok
}

process_build()
{
  prepare_package
  configure_stage
  build_stage
  install_package
}

do_actions
