#!/bin/bash
#
# NOTICE: don't set PATH_SEPARATOR like below, it will cause issue that 'checking for
# grep that handles long lines and -e... configure: error: no acceptable grep could 
# be found'
# export PATH_SEPARATOR=";"

FWD=`dirname $(pwd)`
CWD=$(cd `dirname $0`; pwd)
PKG_DEPS='brotli nasm perl zlib zstd'
PKG_NAME=openssl
PKG_VER=3.3.1
PKG_URL=https://github.com/openssl/openssl/releases/download/$PKG_NAME-$PKG_VER/$PKG_NAME-$PKG_VER.tar.gz
PKGS_DIR=$FWD/pkgs
SRC_DIR=$PKGS_DIR/$PKG_NAME-$PKG_VER
BUILD_DIR=$SRC_DIR

. $FWD/utils/common.sh

clean_build()
{
  echo [$0] Cleaning $PKG_NAME $PKG_VER
  cd $CWD
  if [[ -d "$BUILD_DIR" ]]; then
    if [[ "$BUILD_DIR" != "$SRC_DIR" ]]; then
      rm -rf $BUILD_DIR
    else
      pushd $BUILD_DIR
      nmake clean
      popd
    fi
  fi
}

patch_package()
{
  echo [$0] Patching package $PKG_NAME $PKG_VER
  echo [$0] Nothing to do
}

prepare_package()
{
  clean_build
  clean_log
  create_dirs bin include lib share
  display_info
  download_extract $PKG_URL $PKG_NAME-$PKG_VER.tar.gz $PKG_NAME-$PKG_VER
  if [ ! -d "$BUILD_DIR" ]; then mkdir -p "$BUILD_DIR"; fi
}

configure_stage()
{
  echo [$0] Configuring $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  PERL_PREFIX=`grep -E "\w+\s+perl\s+.+" $OK_FILE | awk '{print substr($0, index($0, $4))}' | awk '{$1=$1};1'`
  configure_cmd $(unix_path "$PERL_PREFIX/bin/perl.exe") Configure VC-WIN64A --prefix=$PREFIX_W --openssldir="$PREFIX_W\\ssl"
}

patch_stage()
{
  cd $BUILD_DIR
  echo [$0] Patching makefile in top level
  sed                                                                                          \
    -e 's|$(INSTALLTOP)\\html\\man1|$(INSTALLTOP)\\share\\html\\man1|g'                        \
    -e 's|$(INSTALLTOP)\\html\\man3|$(INSTALLTOP)\\share\\html\\man3|g'                        \
    -e 's|$(INSTALLTOP)\\html\\man5|$(INSTALLTOP)\\share\\html\\man5|g'                        \
    -e 's|$(INSTALLTOP)\\html\\man7|$(INSTALLTOP)\\share\\html\\man7|g'                        \
    makefile > makefile-t
  mv makefile-t makefile
}

build_stage()
{
  echo [$0] Building $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  build_cmd nmake
}

install_package()
{
  echo [$0] Installing $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  install_cmd nmake install INSTALLDIR=$PREFIX_W
  clean_build
  build_ok
}

process_build()
{
  prepare_package
  configure_stage
  patch_stage
  build_stage
  install_package
}

do_actions
