#!/bin/bash
#
# NOTICE: don't set PATH_SEPARATOR like below, it will cause issue that 'checking for
# grep that handles long lines and -e... configure: error: no acceptable grep could 
# be found'
# export PATH_SEPARATOR=";"

FWD=`dirname $(pwd)`
CWD=$(cd `dirname $0`; pwd)
PKG_DEPS='bzip2 zlib'
PKG_NAME=pcre2
PKG_VER=10.44
PKG_URL=https://github.com/PCRE2Project/pcre2/releases/download/pcre2-$PKG_VER/$PKG_NAME-$PKG_VER.tar.bz2
PKGS_DIR=$FWD/pkgs
SRC_DIR=$PKGS_DIR/$PKG_NAME-$PKG_VER
BUILD_DIR=$FWD/out/$PKG_NAME-$PKG_VER

. $FWD/utils/common.sh

clean_build()
{
  echo [$0] Cleaning $PKG_NAME $PKG_VER
  cd $CWD
  if [[ -d "$BUILD_DIR" ]]; then
    if [[ "$BUILD_DIR" != "$SRC_DIR" ]]; then
      rm -rf $BUILD_DIR
    else
      pushd $BUILD_DIR
      ninja clean
      popd
    fi
  fi
}

patch_package()
{
  echo [$0] Patching package $PKG_NAME $PKG_VER
  pushd $SRC_DIR
  patch -Np1 -i $PATCHES_DIR/001-pcre2-10.43-fix-cmake-files-output-location.diff
  popd
}

prepare_package()
{
  clean_build
  clean_log
  create_dirs bin include lib share
  display_info
  download_extract $PKG_URL $PKG_NAME-$PKG_VER.tar.bz2 $PKG_NAME-$PKG_VER
  if [[ ! -d "$BUILD_DIR" ]]; then mkdir -p "$BUILD_DIR"; fi
}

configure_stage()
{
  echo [$0] Configuring $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  configure_options
  # NOTE:
  # 1. Don't install cygwin's cmake because it will use gcc-like compile
  #    command. To use windows's cmake, here have to use 'cygpath -m' to
  #    convert path to windows path but not cygwin path
  # 2. Don't set cmake generator to 'Unix Makefiles' if use MSYS2 shell
  configure_cmd cmake -G "Ninja"                                                     \
    -DBUILD_SHARED_LIBS=ON                                                           \
    -DCMAKE_BUILD_TYPE=Release                                                       \
    -DCMAKE_C_COMPILER=cl                                                            \
    -DCMAKE_C_FLAGS="$OPTIONS $DEFINES -I${PREFIX_PATH_M//;/ -I}"                    \
    -DCMAKE_CXX_COMPILER=cl                                                          \
    -DCMAKE_CXX_FLAGS="-EHsc $OPTIONS $DEFINES -I${PREFIX_PATH_M//;/ -I}"            \
    -DCMAKE_INSTALL_PREFIX="$PREFIX_M"                                               \
    -DCMAKE_PREFIX_PATH="$PREFIX_PATH_M"                                             \
    -DCMAKE_POLICY_DEFAULT_CMP0026=OLD                                               \
    -DPCRE2_BUILD_PCRE2_16=ON                                                        \
    -DPCRE2_BUILD_PCRE2_32=ON                                                        \
    -DPCRE2_BUILD_PCRE2_8=ON                                                         \
    -DPCRE2_BUILD_PCRE2GREP=ON                                                       \
    -DPCRE2_BUILD_TESTS=OFF                                                          \
    -DPCRE2_NEWLINE=LF                                                               \
    -DPCRE2_STATIC_RUNTIME=OFF                                                       \
    -DPCRE2_SUPPORT_BSR_ANYCRLF=ON                                                   \
    -DPCRE2_SUPPORT_JIT=ON                                                           \
    -DPCRE2_SUPPORT_LIBBZ2=ON                                                        \
    -DPCRE2_SUPPORT_LIBZ=ON                                                          \
    -DPCRE2_SUPPORT_JIT=OFF                                                          \
    -DPCRE2_SUPPORT_UNICODE=ON                                                       \
    $SRC_DIR_M
}

build_stage()
{
  echo [$0] Building $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  build_cmd ninja -j$(nproc)
}

install_package()
{
  echo [$0] Installing $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  install_cmd ninja install
  clean_build
  build_ok
}

process_build()
{
  prepare_package
  configure_stage
  build_stage
  install_package
}

do_actions
