#!/bin/bash
#
# NOTICE: don't set PATH_SEPARATOR like below, it will cause issue that 'checking for
# grep that handles long lines and -e... configure: error: no acceptable grep could 
# be found'
# export PATH_SEPARATOR=";"

FWD=`dirname $(pwd)`
CWD=$(cd `dirname $0`; pwd)
PKG_DEPS=
PKG_NAME=perl
PKG_VER=5.38.2
PKG_URL=https://www.cpan.org/src/${PKG_VER%%.*}.0/$PKG_NAME-$PKG_VER.tar.gz
PKGS_DIR=$FWD/pkgs
SRC_DIR=$PKGS_DIR/$PKG_NAME-$PKG_VER
BUILD_DIR=$SRC_DIR/win32

. $FWD/utils/common.sh

clean_build()
{
  echo [$0] Cleaning $PKG_NAME $PKG_VER
  cd $CWD
  if [[ -d "$BUILD_DIR" ]]; then
    if [[ "$BUILD_DIR" != "$SRC_DIR" ]]; then
      rm -rf $BUILD_DIR
    else
      pushd $BUILD_DIR
      nmake clean CCTYPE=MSVC143 INST_DRV= INST_TOP=$PREFIX_W INST_HTML="$PREFIX_W\\share\\html" 
      popd
    fi
  fi
}

patch_package()
{
  echo [$0] Patching package $PKG_NAME $PKG_VER
  pushd $SRC_DIR
  patch -Np1 -i $PATCHES_DIR/001-perl-5.38.2-fix-nmake-makefiles-errors-on-cygwin.diff
  popd
}

prepare_package()
{
  clean_build
  clean_log
  create_dirs bin lib share
  display_info
  download_extract $PKG_URL $PKG_NAME-$PKG_VER.tar.gz $PKG_NAME-$PKG_VER
  if [ ! -d "$BUILD_DIR" ]; then mkdir -p "$BUILD_DIR"; fi
}

build_stage()
{
  echo [$0] Building $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  build_cmd nmake CCTYPE=MSVC143 INST_DRV= INST_TOP=$PREFIX_W INST_HTML="$PREFIX_W\\share\\html"
}

install_package()
{
  echo [$0] Installing $PKG_NAME $PKG_VER
  cd $BUILD_DIR
  install_cmd nmake install CCTYPE=MSVC143 INST_DRV= INST_TOP=$PREFIX_W INST_HTML="$PREFIX_W\\share\\html"
  clean_build
  build_ok
}

process_build()
{
  prepare_package
  build_stage
  install_package
}

do_actions
