name: xapian-core
version: 1.4.25
url: https://oligarchy.co.uk/xapian/1.4.25/xapian-core-1.4.25.tar.xz
sha256: 0c99dfdd817571cb5689bc412a7e021407938313f38ea3a70fa3bf86410608ee
dependencies:
  required:
    - dlfcn-win32
    - getopt
    - tcl
    - perl
    - zlib
run: build.sh
