name: DirectX-Headers
version: 1.614.1
url: https://github.com/microsoft/DirectX-Headers/archive/refs/tags/v1.614.1.tar.gz
sha256: 344eb454c979ea68d8255d82c818bf7daf01f5109d26ac104f9911d18fae3b21
dependencies:
  required:
    - pkg-config
run: build.bat
