name: diffutils
version: 0.3.10
url: https://ftp.gnu.org/gnu/diffutils/diffutils-3.10.tar.xz
sha256: 90e5e93cc724e4ebe12ede80df1634063c7a855692685919bfe60b556c9bd09e
steps:
  one:
    dependencies:
      - getopt
      - libiconv
      - libsigsegv
      - gettext
      - winpthreads
    run: build.sh
