name: KTX-Software
version: 4.4.0
url: https://github.com/KhronosGroup/KTX-Software/archive/refs/tags/v4.4.0.tar.gz
sha256: 3585d76edcdcbe3a671479686f8c81c1c10339f419e4b02a9a6f19cc6e4e0612
dependencies:
script: build.bat
