name: gsl
version: 2.8
url: https://ftp.gnu.org/gnu/gsl/gsl-2.8.tar.gz
sha256: 6a99eeed15632c6354895b1dd542ed5a855c0f15d9ad1326c6fe2b2c9e423190
dependencies:
  required:
    - dlfcn-win32
    - libiconv
script: build.sh
