name: llvm-project
version: 19.1.7
url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-19.1.7.tar.gz
sha256: 59abea1c22e64933fad4de1671a61cdb934098793c7a31b333ff58dc41bff36c
steps:
  a:
    dependencies:
      - dlfcn-win32
      - libffi
      - libxml2
      - lua
      - perl
      - xz
      - zlib
      - zstd
      - winpthreads
    run: build.bat
