name: llvm-project
version: 20.1.6
url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-20.1.6.tar.gz
sha256: afa487c401613f5e4a35935b2abfb5d07e6ebfa20df32787e34a5c7e97c6ea4b
steps:
  a:
    dependencies:
      - dlfcn-win32
      - libffi
      - libxml2
      - lua
      - perl
      - xz
      - zlib
      - zstd
      - winpthreads
    run: build.bat
