name: llvm-project
version: 20.1.7
url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-20.1.7.tar.gz
sha256: 91865189d0ca30ca81b7f7af637aca745b6eeeba97c5dfb0ab7d79a1d9659289
steps:
  a:
    dependencies:
      - dlfcn-win32
      - libffi
      - libxml2
      - lua
      - perl
      - xz
      - zlib
      - zstd
      - winpthreads
    run: build.bat
