name: llvm-project
version: 20.1.1
url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-20.1.1.tar.gz
sha256: edde69aa3e48a3892a8f01332ff79cfb6179151b42503c4ba77d2cd408b013bf
steps:
  a:
    dependencies:
      - dlfcn-win32
      - libffi
      - libxml2
      - lua
      - perl
      - xz
      - zlib
      - zstd
      - winpthreads
    run: build.bat
