name: Couenne
version: master
url: https://github.com/coin-or/Couenne.git
sha256:
steps:
  a:
    dependencies:
      - BuildTools
      - CoinUtils
      - ThirdParty-ASL
      - ThirdParty-HSL
      - ThirdParty-Mumps
      - Data-Sample
      - Osi
      - Clp
      - Cgl
      - Cbc
      - Ipopt
      - Bonmin
    run: build.sh
