name: Couenne
version: master
url: https://github.com/coin-or/Couenne.git
recursive: false
depth: 1
dependencies:
  required:
    - BuildTools
    - CoinUtils
    - ThirdParty-ASL
    - ThirdParty-Mumps
    - Data-Sample
    - Osi
    - Clp
    - Cgl
    - Cbc
    - Ipopt
    - Bonmin
run: build.sh
