name: libaom
version: 3.9.1
url: https://storage.googleapis.com/aom-releases/libaom-3.9.1.tar.gz
sha256: dba99fc1c28aaade28dda59821166b2fa91c06162d1bc99fde0ddaad7cecc50e
steps:
  a:
    dependencies:
      - yasm
      - perl
      - winpthreads
    run: build.bat
