name: libaom
version: 3.12.0
url: https://storage.googleapis.com/aom-releases/libaom-3.12.0.tar.gz
sha256: d89daa160a0ea1409c4193be5b17c9591024c4f5a0e545dcb9d197535c66836e
dependencies:
  required:
    - yasm
    - perl
    - winpthreads
run: build.bat
