name: help2man
version: 1.49.3
url: https://ftp.gnu.org/gnu/help2man/help2man-1.49.3.tar.xz
sha256: 4d7e4fdef2eca6afe07a2682151cea78781e0a4e8f9622142d9f70c083a2fd4f
dependencies:
  required:
    - gettext
script: build.sh
