name: libgav1
version: 0.19.0
url: https://github.com/mirrorstogooglesource/libgav1/archive/refs/tags/v0.19.0.tar.gz
sha256: 156a831e236560508a591b386fee8b7b77c73278ea0609cbc7fb4256b244debf
steps:
  one:
    dependencies:
      - abseil-cpp
      - googletest
      - winpthreads
    run: build.bat
