name: plasma
version: 25.5.27
url: https://github.com/icl-utk-edu/plasma/archive/refs/tags/25.5.27.tar.gz
sha256: 3e4fff29f55bd28fee27d54346c425bbec91d64a726a84fd96a13d4234b6df34
dependencies:
  required:
    - OpenBLAS
script: build.bat
