name: lzo
version: "2.10"
url: https://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz
sha256: c0f892943208266f9b6543b3ae308fab6284c5c90e627931446fb49b4221a072
steps:
  one:
    dependencies:
      - dlfcn-win32
    run: build.sh
