name: libavif
version: 1.3.0
url: https://github.com/AOMediaCodec/libavif/archive/refs/tags/v1.3.0.tar.gz
sha256: 0a545e953cc049bf5bcf4ee467306a2f113a75110edf59e61248873101cd26c1
dependencies:
  required:
    - dav1d
    - libaom
    - libyuv
    - libgav1
    - rav1e
    - SVT-AV1
script: build.bat
