name: mm-common
version: 1.0.6
url: https://download.gnome.org/sources/mm-common/1.0/mm-common-1.0.6.tar.xz
sha256: b55c46037dbcdabc5cee3b389ea11cc3910adb68ebe883e9477847aa660862e7
dependencies:
  required:
    - pkg-config
script: build.bat
