name: scotch
version: 7.0.6
url: https://gitlab.inria.fr/scotch/scotch/-/archive/v7.0.6/scotch-v7.0.6.tar.bz2
sha256: 8168bf3f8025bb27be6dc9e055c4ceb58c09979c1c04a50ca251da021f12dbbe
dependencies:
  required:
    - bzip2
    - winflexbison
    - winpthreads
    - xz
    - zlib
script: build.bat
