name: soplex
version: 7.1.3
url: https://github.com/scipopt/soplex/archive/refs/tags/release-713.tar.gz
sha256: 3d2039c9175e55571dc97b154ef23096ee8b6752085d5d9b07c530beb23f2d09
dependencies:
  required:
    - boost
    - zlib
    - gmp
    - mpfr
    - papilo
    - winpthreads
run: build.bat
