name: OpenVDB
version: 12.0.1
url: https://github.com/AcademySoftwareFoundation/openvdb/archive/refs/tags/v12.0.1.tar.gz
sha256: a3c8724ecadabaf558b6e1bd6f1d695e93b82a7cfdf144b8551e5253340ddce0
steps:
  a:
    dependencies:
      - boost
      - oneTBB
      - c-blosc
      - zlib
    run: build.bat
