name: glibmm
version: 2.82.0
url: https://download.gnome.org/sources/glibmm/2.82/glibmm-2.82.0.tar.xz
sha256: 38684cff317273615c67b8fa9806f16299d51e5506d9b909bae15b589fa99cb6
steps:
  a:
    dependencies:
      - mm-common
      - pkg-config
      - glib:b
      - libsigc++
    run: build.bat
