name: protobuf
version: 28.3
url: https://github.com/protocolbuffers/protobuf/archive/refs/tags/v28.3.tar.gz
sha256: 7c3ebd7aaedd86fa5dc479a0fda803f602caaf78d8aff7ce83b89e1b8ae7442a
steps:
  a:
    dependencies:
      - abseil-cpp
      - winpthreads
    run: build.bat
