name: protobuf
version: 29.3
url: https://github.com/protocolbuffers/protobuf/archive/refs/tags/v29.3.tar.gz
sha256: 008a11cc56f9b96679b4c285fd05f46d317d685be3ab524b2a310be0fbad987e
steps:
  a:
    dependencies:
      - abseil-cpp
      - winpthreads
    run: build.bat
