name: volk
version: 1.4.304
url: https://github.com/zeux/volk/archive/refs/tags/1.4.304.tar.gz
sha256: ab3d4a8ccaeb32652259cdd008399504a41792675b0421d90b67729ee274746f
steps:
  a:
    dependencies:
      - Vulkan-Headers
      - Vulkan-Utility-Libraries
    run: build.bat
