name: gzip
version: 1.13
url: https://ftp.gnu.org/gnu/gzip/gzip-1.13.tar.xz
sha256: 7454eb6935db17c6655576c2e1b0fabefd38b4d0936e0f87f48cd062ce91a057
dependencies:
  required:
    - dirent
    - getopt
run: build.sh
