name: vala
version: 0.56.17
url: https://download.gnome.org/sources/vala/0.56/vala-0.56.17.tar.xz
sha256: 26100c4e4ef0049c619275f140d97cf565883d00c7543c82bcce5a426934ed6a
steps:
  one:
    dependencies:
      - getopt
      - gettext
      - gobject-introspection
      - glib:two
      - graphviz
      - harfbuzz:two
      - libiconv
      - pixman
    run: build.sh