name: re2
version: 2024-07-02
url: https://github.com/google/re2/archive/refs/tags/2024-07-02.tar.gz
sha256: eb2df807c781601c14a260a507a5bb4509be1ee626024cb45acbd57cb9d4032b
dependencies:
  required:
    - abseil-cpp
    - winpthreads
run: build.bat
