name: indent
version: 2.2.13
url: https://ftp.gnu.org/gnu/indent/indent-2.2.13.tar.xz
sha256: 1b81ba4e9a006ca8e6eb5cbbe4cf4f75dfc1fc9301b459aa0d40393e85590a0b
dependencies:
  required:
    - dirent
    - libiconv
    - gettext
run: build.sh
