name: cmh
version: 1.1.1
url: https://www.multiprecision.org/downloads/cmh-1.1.1.tar.gz
sha256: 214d5d51fea4af54cda85ef9aee43eff8a711b725a527574d0f3b5581dde4d59
dependencies:
  required:
    - pkg-config
    - gmp
    - fplll
    - mpfr
    - mpfrcx
    - mpc
    - pari
run: build.sh
