name: pkg-config
version: 0.29.2
url: https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
sha256: 6fc69c01688c9458a57eb9a1664c9aba372ccda420a02bf4429fe610e7e7d591
steps:
  a:
    dependencies:
      - dlfcn-win32
      - dirent
    run: build.sh
