name: HiGHS
version: 1.7.1
url: https://github.com/ERGO-Code/HiGHS/archive/refs/tags/v1.7.1.tar.gz
sha256: 65c6f9fc2365ced42ee8eb2d209a0d3a7942cd59ff4bd20464e195c433f3a885
steps:
  one:
    dependencies:
      - zlib
    run: build.bat
