name: spdlog
version: 1.15.0
url: https://github.com/gabime/spdlog/archive/refs/tags/v1.15.0.tar.gz
sha256: 9962648c9b4f1a7bbc76fd8d9172555bad1871fdb14ff4f842ef87949682caa5
steps:
  one:
    dependencies:
      - Catch2
      - fmt
      - benchmark
      - winpthreads
    run: build.bat
