name: Dip
version: 0.95.1
url: https://github.com/coin-or/Dip/archive/refs/tags/releases/0.95.1.tar.gz
sha256: 064deaaee854ad6cf865501cbfc8864c066ab9d8af9d15d4cbe0b4599782c6db
dependencies:
  required:
    - Data-Sample
    - CoinUtils
    - Osi
    - Clp
    - Cgl
    - Cbc
    - CHiPPS-ALPS
    - SYMPHONY
script: build.sh
