name: libdatrie
version: 0.2.13
url: https://github.com/tlwg/libdatrie/archive/refs/tags/v0.2.13.tar.gz
sha256: e16c4e684b1d52b028a486c972f882e977b44c091ea3925f638ba3ae6d169e06
steps:
  a:
    dependencies:
      - dlfcn-win32
      - libiconv
    run: build.sh
