name: libdatrie
version: 0.2.13
url: https://github.com/tlwg/libdatrie/archive/refs/tags/v0.2.13.tar.gz
steps:
  one:
    dependencies:
      - dlfcn-win32
      - doxygen
      - libiconv
    run: build.sh
