name: brotli
version: 1.1.0
url: https://github.com/google/brotli/archive/refs/tags/v1.1.0.tar.gz
sha256: e720a6ca29428b803f4ad165371771f5398faba397edf6778837a18599ea13ff
steps:
  one:
    dependencies:
    run: build.bat
