name: yaml
version: 0.2.5
url: http://pyyaml.org/download/libyaml/yaml-0.2.5.tar.gz
sha256: c642ae9b75fee120b2d96c712538bd2cf283228d2337df2cf2988e3c02678ef4
steps:
  one:
    dependencies:
      - dlfcn-win32
    run: build.sh
