name: libheif
version: 1.19.5
url: https://github.com/strukturag/libheif/archive/refs/tags/v1.19.5.tar.gz
sha256: 5cd9a3e28493310358e1c1299cd596cc4c7ae5fb985eceb758fa6141424e58bb
steps:
  a:
    dependencies:
      - dav1d
      - getopt
      - kvazaar
      - libaom
      - libde265
      - libjpeg-turbo
      - libpng
      - SVT-AV1
      - libtiff:b
      - uvg266
      - zlib
      - openh264
      - OpenJPH
      - VVdeC
      - VVenC
    run: build.bat
