name: librsvg
version: 2.59.91
url: https://download.gnome.org/sources/librsvg/2.59/librsvg-2.59.91.tar.xz
sha256: b1ff70d5b04441ba2ba3f80404b7d98127128fba1020211e3d99b7bf400e4f83
steps:
  a:
    dependencies:
      - cairo
      - cargo-c
      - gobject-introspection:b
      - glib:b
      - freetype
      - pkg-config
      - pango
      - gdk-pixbuf
      - libxml2
      - vala
    run: build.bat
