name: librsvg
version: 2.59.90
url: https://download.gnome.org/sources/librsvg/2.59/librsvg-2.59.90.tar.xz
sha256: d3d623a9839d2b7eb76a5b0b621c15d02abc4d9a886376c3a53b568206ebf545
steps:
  a:
    dependencies:
      - cairo
      - cargo-c
      - gobject-introspection:b
      - glib:b
      - freetype
      - pkg-config
      - pango
      - gdk-pixbuf
      - libxml2
      - vala
    run: build.bat
