name: AviSynthPlus
version: 3.7.3
url: https://github.com/AviSynth/AviSynthPlus/archive/refs/tags/v3.7.3.tar.gz
sha256: b847705af6f16fa26664d06e0fea2bda14a7f6aac8249a9c37e4106ecb8fd44c
steps:
  a:
    dependencies:
    run: build.bat
