name: mpfun-fort
version: v24
url: https://www.davidhbailey.com/dhbsoftware/mpfun-fort-v24.tar.gz
sha256: e4226724bb78bf56100582422243075e693f5f9e1a676bea0e6e8b03da42c542
steps:
  a:
    dependencies:
    run: build.bat
