name: json-glib
version: 1.10.0
url: https://gitlab.gnome.org/GNOME/json-glib/-/archive/1.10.0/json-glib-1.10.0.tar.bz2
steps:
  one:
    dependencies:
      - dlfcn-win32
      - pkg-config
      - glib:two
      - gobject-introspection
    run: build.bat
