name: json-glib
version: 1.10.0
url: https://gitlab.gnome.org/GNOME/json-glib/-/archive/1.10.0/json-glib-1.10.0.tar.bz2
sha256: 9525b85efec2fec22112a9ade2f48595e9711563617e0c80da4b1bfa0313b9e9
dependencies:
  required:
    - dlfcn-win32
    - pkg-config
    - glib
run: build.bat
