name: sed
version: 4.9
url: https://ftp.gnu.org/pub/gnu/sed/sed-4.9.tar.xz
sha256: 6e226b732e1cd739464ad6862bd1a1aba42d7982922da7a53519631d24975181
steps:
  a:
    dependencies:
      - gettext
      - getopt
      - gnulib
      - libiconv
      - winpthreads
    run: build.sh
