name: libev
version: 4.33
url: https://dist.schmorp.de/libev/libev-4.33.tar.gz
sha256: 507eb7b8d1015fbec5b935f34ebed15bf346bed04a11ab82b8eee848c4205aea
steps:
  a:
    dependencies:
    run: build.sh
