name: libheif
version: 1.20.2
url: https://github.com/strukturag/libheif/archive/refs/tags/v1.20.2.tar.gz
sha256: b70340395d84184bb8dfc833dd51c95ae049435f7ff9abc7b505a08b5ee2bd2a
dependencies:
  required:
    - dav1d
    - doxygen
    - ffmpeg
    - getopt
    - kvazaar
    - libaom
    - libde265
    - libjpeg-turbo
    - libpng
    - SVT-AV1
    - libtiff
    - uvg266
    - vmaf
    - x265
    - zlib
    - openh264
    - OpenJPH
    - VVdeC
    - VVenC
    - rav1e
  optional:
    - graphviz:required
script: build.bat
