name: harfbuzz
version: 10.0.1
url: https://github.com/harfbuzz/harfbuzz/archive/refs/tags/10.0.1.tar.gz
sha256: e7358ea86fe10fb9261931af6f010d4358dac64f7074420ca9bc94aae2bdd542
steps:
  one:
    dependencies:
      - pkg-config
      - icu4c
      - libpng
    run: build.bat
  two:
    dependencies:
      - pkg-config
      - gobject-introspection
      - glib:two
      - cairo
      - freetype
      - icu4c
      - libpng
    run: build.bat
